<?php
/**
 * @category   Auguria
 * @package    Auguria_Video
 * @author     Auguria
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
<?php
	$_item = $this->getVideo();
  	if ($_item):
  		if ($this->getItemImage($_item)!=false):
?>
  	<div id="video-player-container" style="display:none">
  		<iframe id="video-player" width="<?php echo  Mage::getStoreConfig('auguria_video/sizes/video_player_width'); ?>" height="<?php echo  Mage::getStoreConfig('auguria_video/sizes/video_player_height'); ?>" src="" frameborder="0" allowfullscreen></iframe>
	</div>
	<div id="home_video_preview" class="link">
		<div class="hvp_play"></div>
		<img src="<?php echo $this->getItemImage($_item); ?>" alt="<?php echo $_item->getTitle(); ?>" />
		<div><?php echo $_item->getDescription(); ?></div>
	</div>
<script type="text/javascript">
//<![CDATA[
	Event.observe('home_video_preview', 'click', function(event) {
		videoPlayer = new Window({
			className:'magento',
			title:'<?php echo $_item->getTitle(); ?>',
			content:$('video-player'),
			width:<?php echo  Mage::getStoreConfig('auguria_video/sizes/video_player_width'); ?>,
			height:<?php echo  Mage::getStoreConfig('auguria_video/sizes/video_player_height')+5; ?>,
			minimizable:false,
			maximizable:false,
			showEffectOptions:{duration:0.4},
			hideEffectOptions:{duration:0.4},
			onClose:function(event) { $('video-player').src=""; }
		});
		videoPlayer.setZIndex(100);
		videoPlayer.showCenter(true);
		$('video-player').src="http://www.youtube.com/v/<?php echo $_item->getImageIdentifier(); ?>&hl=fr&autoplay=1";
		videoPlayer.getContent().update($('video-player'));
	});
//]]>
</script>

<?php
		endif;
	endif;
?>
