<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>



		<form method="get" action="<?php echo $this->getFormActionUrl() ?>" id="blog-search-form">
			<div class="blog-search sidebar">
				<input type="text" name="s" class="input-text" title="<?php echo $this->__('Discover') ?>" value="<?php echo $this->escapeHtml($this->getSearchTerm()) ?>"/>
				<button class="button" title="<?php echo $this->__('Discover') ?>" type="submit"></button>
				<script type="text/javascript">new fishpig.WP.Search.Form('blog-search-form');</script>
			</div>
		</form>
