   <div style="margin-top:92px" class="duoflexlanding page odd section">

		<div style="height:627px;background:#000 url(<?php echo $this->getSkinUrl(); ?>images/duoflex-landing-page/bkg_duoflex1.jpg) center top no-repeat;">

			 <div style="margin-bottom:0px" class="content">

			<div class="dfheadline">
				<div class="dftitle">
					<p style="margin-bottom:14px;color:#fff;font-size:21px">INTRODUCING the</p>
					<h1><span style="text-shadow:0px 1px 0px #000;" class="pirulen">DUO-</span><span class="markerfeltthin">Flex</span></h1>
					<p style="text-shadow:0px 1px 0px #000;margin-bottom:40px;margin-top:15px;color:#fff;font-size:23px">A Portable Sun Powered Charging System</p>

				</div>

					<p style="margin-bottom:16px;float:left"><span style="color:#fff !important;font-size:25px">limited time:</span>&nbsp;&nbsp;<span style="color:#fff;font-size:29px;font-weight:bold">$159.99</span></p>
					<p><span style="margin-left:25px;text-decoration:line-through;color:#f6af00;font-size:14px;">was $199.99</span></p>
					
					<div class="clear"></div>

					<a style="float:left;" href="<?php echo Mage::getBaseUrl(); ?>duo-flex-solar-charger.html" class="buyitnow grey"><span>buy it now</span></a>

					<?php /* <a href="#" class="learnmorea" style="line-height:52px;color:#fff;font-size:15px;margin-left:25px;" id="learnmore">or learn more</a> 
					
					<script type="text/javascript">
					jQuery( ".learnmorea" ).click(function() {

						jQuery("html, body").animate({ scrollTop: jQuery('#fourblock').offset().top-85 }, 1000);
					});
					</script>
					
					
					*/ ?>
					<div style="padding-top:10px;display:table-cell;padding-left:25px;color:#fff;">
						<span style="font-size:17px;">Use coupon <strong>SOLAR15</strong> at checkout</span><br/>
						<span style="font-size:13px;">offer expires 4/15/14</span>
					</div>

					


					<div class="clear"></div>

					

					<h1 class="freedomis">freedom is being fully <span style="font-weight: bold" class="yellow">charged</span></h1>
					
					<div style="color:#fff;margin-bottom:0px" class="fourblock">

						<div style="width:260px;height:43px;margin-top:20px;" class="durable">
							<h4>DURABLE LIGHTWEIGHT DESIGN</h4>
						</div>

						<div style="width:260px;height:43px;margin-top:20px;" class="dual">
							<h4>Dual Configuration</h4>
						</div>

						<div class="clear"></div>

						<div style="width:260px;height:43px;" class="fast">
							<h4>FAST CHARGING USB</h4>
						</div>

						<div style="width:260px;height:43px;" class="battery">
							<h4 style="text-transform:none">8000 mAh REMOVABLE BATTERY</h4>
						</div>

					</div>

					<div class="clear"></div>
			 </div>

			</div>

		</div>

	<div style="height:216px;background:#000 url(<?php echo $this->getSkinUrl(); ?>images/duoflex-landing-page/bkg_duoflex2.jpg) center top no-repeat;"></div>



		<div style="height:1269px;background:#000 url(<?php echo $this->getSkinUrl(); ?>images/duoflex-landing-page/bkg_bodytop.jpg) center top no-repeat;">

			<div style="margin-bottom:0px !mportant" class="bodytop content">
				<div>
					<h2>Portable Solar Power without limitations.</h2>

					<p style="margin-bottom:55px;line-height:22px;font-size:19px;color:#fff;">Whether you're back packing, mountain biking, heading out for a family vacation, or just in<br/>need of staying fully charged at all times, the DUO-Flex fits each and every need.</p>
					
					<div style="width:198px;text-align:center;margin:0px auto;">
						<a style="margin-left:10px;" href="<?php echo Mage::getBaseUrl(); ?>duo-flex-solar-charger.html" class="buyitnow black"><span>buy it now</span></a>
					</div>
		

					<h3>All it takes is <span style="font-style:italic">three easy steps</span> to keep charged all day long.</h3>
				</div>

				<div class="thrcircles">
					<div style="width:412px">
						<p>Unfold the DUO-Flex and configure a<br/>layout that best fits your environment.</p>
						<span>STEP<br/>1</span>
					</div>


					<div style="width:355px">
						<p>Connect the included battery for a<br/>full charge in as few as five hours.</p>
						<span>STEP<br/>2</span>
					</div>


					<div style="width:385px">
						<p >Plug your devices into the battery,<br/>and experience the freedom of<br/>being fully charged.</p>
						<span>STEP<br/>3</span>
					</div>

					<div class="clear"></div>
				</div>



				<h4 style="margin-bottom:62px;color:#fff;font-weight:bold;font-size:45px;">Freedom is being fully <span style="color:#f2cb23;">charged.</span></h4>


				



			</div>

		</div>

		<div style="height:207px;background:#fff">
			<div class="content">
				<div class="bodytopbtm" style="width:515px;">
					<p>The DUO-Flex is the only solar panel that comes with a battery backup,<br/>providing enough power to charge your smart phone up to 6 times - and<br/>small enough to fit in your back pocket!</p>
				</div>

				<div class="bodytopbtm" style="margin-left:118px;width:520px;">
					<p>Move at the speed of life without having to worry about plugging in.<br/>The DUO-Flex provides you with the freedom to explore, play, fly, and <br/>more - all while staying in touch with the things that matter the most to you. </p>

				</div>

				<div class="clear"></div>
			
			</div>
		
		</div>

	

		<div style="text-align:center;height:954px;background:#000;color:#fff;">
			<h2 style="padding-top:74px;font-size:25px;font-weight:bold;">DURABLE DUAL CONFIGURATION</h2>

			<h3 style="padding-top:15px;font-size:19px;">Put the power of the sun in the palm of your hand.</h3>

			<p style="padding-top:2px;line-height:18px;font-size:14px;">With your busy life, you demand a solar charger as flexible as you, which can provide portable power rain or shine. With multiple<br/>configurations and a portable battery pack, the DUO-Flex is the only portable solar charging solution that is truly limitless.</p>
			
			<div style="width:415px;margin: 0 auto;">
			<div style="line-height:18px;margin-top:10px;font-weight:bold;font-size:15px;color:#f7bc16;float:left">
						Vertical Dimensions: 27.2 x 11 x 0.6 in.<br/>
						Square Dimensions: 18.1 x 15 x 0.6 in.
			</div>
			<div style="line-height:18px;margin-top:21px;float:left;">
				<span style="height:17px !important;color:#f7bc16;display:block;font-weight:bold;font-size:15px;padding-left:16px;margin-left:16px;border-left:2px solid #9d8129">Weight: 1.5 lbs.</span>
			</div>

			<div class="clear"></div>
			</div>

			<div style="margin:60px 0px 0px 0px;height:225px;background:url(<?php echo $this->getSkinUrl(); ?>images/duoflex-landing-page/bkg_configuration.png) center top no-repeat;"></div>

			<div style="margin-bottom:0px" class="fourblock content">

				<div class="durable">
					<h4>DURABLE LIGHTWEIGHT DESIGN</h4>
					<p>Featuring flexible mono-crystalline PV design, you don't need to worry about damaging the cells while in use. Even the side pocket which houses your battery pack and mobile device has a built in water resistant zipper to keep your electronics safe in various weather conditions.</p>

				</div>

				<div class="dual">
					<h4>Dual Configuration</h4>
					<p>Configure the water-resistant solar panels in a vertical or square position to fit various applications depending on your needs. Whether you need to a backpack or lay it on your dashboard, the DUO-Flex will offer you the most convenient solar charge.</p>
				</div>

				<div class="clear"></div>

				<div class="fast">
					<h4>FAST CHARGING USB</h4>
					<p>The battery pack features two USB outputs, 5V 1A & 2A , giving you the ultimate charging capability. Whether you're charging a phone, tablet, or camera, your device will charge as fast as plugging into a wall.</p>

				</div>

				<div class="battery">
					<h4 style="text-transform:none">8000 mAh REMOVABLE BATTERY</h4>
					<p>High capacity portable battery pack has enough power to charge a smart phone up to 6 times, a tablet 1 time, or a point and shoot USB camera up to 14 times.</p>
				</div>

			</div>
				<div class="clear"></div>
			<a style="margin:15px auto 0px auto;" href="<?php echo Mage::getBaseUrl(); ?>duo-flex-solar-charger.html" class="buyitnow yellow"><span>buy it now</span></a>
		</div>

<div class="footer-container">

	<div class="specif content">
		<p style="margin-bottom:10px;font-size:16px;font-weight:bold;">SPECIFICATIONS:</p>

		<div style="font-size:13px;float:left;width:350px;">
			<strong>GENERAL SPECS</strong><br/>
			<strong>Dimensions:</strong><br/>
			Packed: 13.4"H x 8.3"L x 0.8"D<br/>
			Deployed Vertical: 27.2"H x 11"L x 0.6"D<br/>
			Deployed Horizontal: 18.1"H x 15"L x 0.6"D<br/>
			<br/>
			<strong>Total Weight: </strong>1.5 LBS<br/>
			<strong>Model Number:  </strong>SP-13<br/>

		</div>

		<div style="font-size:13px;float:left;width:270px;">
			<strong>SOLAR PANELS</strong><br/>
			<strong>Rated: </strong>13W<br/>
			<strong>Cell Type: </strong>Mono-crystalline silicon<br/>
			<strong>Output: </strong>USB Micro (DV 5V 1.5A)<br/>

		</div>

		<div style="font-size:13px;float:left;width:262px;">
			<strong>BATTERY</strong><br/>
			<strong>Capacity: </strong>8000mAh LiPo<br/>
			<strong>USB Output: </strong>5V 1A<br/>
			<strong>USB Output: </strong>5V 2A<br/>
			<strong>Charging Input: </strong>USB Micro
		</div>

		<div style="font-size:13px;float:left;width:240px;">
			<span style="display:block;font-size:16px"><strong>THIS BOX ALSO CONTAINS:</strong></span><br/>
			<div style="margin-bottom:20px;text-transform:uppercase;line-height:35px;padding-left:80px;background:url(<?php echo $this->getSkinUrl(); ?>images/duoflex-landing-page/icon_carabiners.png) left no-repeat;height:34px"><strong>4 Carabiners (clips)</strong></div>
			<div style="text-transform:uppercase;line-height:35px;padding-left:80px;background:url(<?php echo $this->getSkinUrl(); ?>images/duoflex-landing-page/icon_acadapter.png) left no-repeat;height:34px"><strong>AC ADAPTER</strong></div>

		</div>
	</div>

	<div class="clear"></div>

	<div style="padding-top:82px" class="footer">
				<div style="padding-top:10px;float:left;margin:0px;width:65%" class="fleft">

					<div class="copyright"><address>Copyright &copy; <?php echo date("Y") ?> AspectSolar<span style="font-size:10px;position: relative; bottom: 0.5ex;">&#174;</span>. All Rights Reserved.</address></div>
				</div>

			<?php /*
			<!-- SOCIAL MEDIA LINKS: -->
			<div style="width:auto;float:right;text-align:right;margin:0px;width:25.3%;" class="last fright">


						<span>STAY CHARGED!</span>
						<div onclick="window.open('https://www.facebook.com/AspectSolarMedia','_blank');" class="fb"></div>
						<div onclick="window.open('https://plus.google.com/+AspectSolarHQ','_blank');" class="google"></div>
						<div onclick="window.open('https://twitter.com/aspectsolar','_blank');" class="twitter"></div>
						<div onclick="window.open('http://www.youtube.com/aspectsolarhq','_blank');" class="youtube last"></div>



		<script type="text/javascript">
						//<![CDATA[
							jQuery(document).ready(function(){
							   jQuery(".footer .fb").hover(function() {
									jQuery(this).animate({opacity: 0}, 120, function() {
										jQuery(this)
											.css({'background-image': 'url(<?php echo $this->getSkinUrl('images/icon_fb-hover.png'); ?>)'})
											.animate({opacity: 1}, 120);
									});
								}, function() {

										jQuery(this).animate({opacity: 0}, 0, function() {
										jQuery(this)
											.css({'background-image': 'url(<?php echo $this->getSkinUrl('images/icon_fb.png'); ?>)'})
											.animate({opacity: 1}, 0);
									});
								});

								jQuery(".footer .google").hover(function() {
									jQuery(this).animate({opacity: 0}, 120, function() {
										jQuery(this)
											.css({'background-image': 'url(<?php echo $this->getSkinUrl('images/icon_google-hover.png'); ?>)'})
											.animate({opacity: 1}, 120);
									});
								}, function() {

										jQuery(this).animate({opacity: 0}, 0, function() {
										jQuery(this)
											.css({'background-image': 'url(<?php echo $this->getSkinUrl('images/icon_google.png'); ?>)'})
											.animate({opacity: 1}, 0);
									});
								});

								jQuery(".footer .linkedin").hover(function() {
									jQuery(this).animate({opacity: 0}, 120, function() {
										jQuery(this)
											.css({'background-image': 'url(<?php echo $this->getSkinUrl('images/icon_linkedin-hover.png'); ?>)'})
											.animate({opacity: 1}, 120);
									});
								}, function() {

										jQuery(this).animate({opacity: 0}, 0, function() {
										jQuery(this)
											.css({'background-image': 'url(<?php echo $this->getSkinUrl('images/icon_linkedin.png'); ?>)'})
											.animate({opacity: 1}, 0);
									});
								});

								jQuery(".footer .twitter").hover(function() {
									jQuery(this).animate({opacity: 0}, 120, function() {
										jQuery(this)
											.css({'background-image': 'url(<?php echo $this->getSkinUrl('images/icon_twitter-hover.png'); ?>)'})
											.animate({opacity: 1}, 120);
									});
								}, function() {

										jQuery(this).animate({opacity: 0}, 0, function() {
										jQuery(this)
											.css({'background-image': 'url(<?php echo $this->getSkinUrl('images/icon_twitter.png'); ?>)'})
											.animate({opacity: 1}, 0);
									});
								});

								jQuery(".footer .youtube").hover(function() {
									jQuery(this).animate({opacity: 0}, 120, function() {
										jQuery(this)
											.css({'background-image': 'url(<?php echo $this->getSkinUrl('images/icon_youtube-hover.png'); ?>)'})
											.animate({opacity: 1}, 120);
									});
								}, function() {

										jQuery(this).animate({opacity: 0}, 0, function() {
										jQuery(this)
											.css({'background-image': 'url(<?php echo $this->getSkinUrl('images/icon_youtube.png'); ?>)'})
											.animate({opacity: 1}, 0);
									});
								});
							});
						//]]>
						</script>
			</div>
			*/ ?>
	</div>
</div>
<!-- Google Code for Remarketing Tag -->
<!--------------------------------------------------
Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
--------------------------------------------------->
<script type="text/javascript">
// var google_tag_params = {
// ecomm_prodid: 'REPLACE_WITH_VALUE',
// ecomm_pagetype: 'REPLACE_WITH_VALUE',
// ecomm_totalvalue: 'REPLACE_WITH_VALUE',
// };
</script>
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 972079564;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/972079564/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
</div>
