

<div class="inner-fullwidth">
	<div class="title">
		<h2>Freedom is a Lifestyle</h2>
		
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_social_icons')->toHtml() ?>
	</div>
	
	<div class="contentbox">
		<div class="frdcont">
			<img src="<?php echo $this->getSkinUrl(); ?>images/energybar.jpg" alt="" title="" />
		
			<h1 class="frdh1">Power your lifestyle with the most versatile<br/>portable battery pack to hit the market.</h1>
			
			<h1 class="pirulen">EnergyBar<span style="font-weight:bold;font-family:Century Gothic;font-size:12px;position: relative; bottom: 3ex;">TM</span> 250</h1>
			
			<div class="frdaction">
				<a class="linkbutton learnmore black" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>learn more</span></a>
				<a class="linkbutton buyitnow" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>buy it now</span></a>
			</div>
			
			<iframe style="margin-bottom:71px;" width="480" height="317" src="//www.youtube.com/embed/408ME2GapWg?wmode=transparent" frameborder="0" allowfullscreen></iframe>
			
			<h1 class="frdh2">freedom is being fully <span class="yellow">charged</span></h1>
				
				
			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img1.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>Travel with it</h5>
					
					<p>The EnergyBar 250 is ultra slim and fits in your suitcase. Weighing slightly less than 8 pounds and providing hours and hours of power, this portable unit will easily become one of your best travel buddies. Recharge it in 5 hours at your hotel or any wall outlet.</p>
				</div>
			</div>
			
			<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img2.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>SAIL WITH IT</h5>
					
					<p>Go anywhere with the EnergyBar 250 and keep it protected with its weather resistant neoprene carrying case.  This case also includes a small pouch for your adapters, accessories, or mobile phones. Zip it closed to keep it from getting wet. Great for powering all of your devices while out on the boat including phones, tablets, SLR camera batteries, or even GPS.</p>
				</div>
			</div>
			
			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img3.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>FLY WITH IT</h5>
					
					<p>Our Lithium Iron Phosphate battery is so light weight that pilots love it. The EnergyBar 250 can power multiple phones or tablets simultaneously for hours.  Pilots can even use this product to power portable air coolers!</p>
				</div>
			</div>
			
			<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img4.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>CAMP WITH IT</h5>
					
					<p>This portable battery pack holds 250 watt hours of power, which is enough power for you to run anything from camping lights, small fans, radios, or even a television. We aren't exactly saying you should bring a TV every time you go camping, but you could!</p>
				</div>
			</div>
			
			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img5.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>TAILGATE WITH IT</h5>
					
					<p>You may not want to bring your television or laptop when you go camping, but why not when you go tailgating? Power your television, radios, phones, tablets, all from the convenience of the EnergyBar 250 battery pack!</p>
				</div>
			</div>
			
			<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img6.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>RECHARGE IT!</h5>
					
					<p>The EnergyBar 250 is truly the most versatile battery pack out there. You can recharge it multiple ways.
					
					<ol class="numbered">
						<li>Charge it from a wall outlet</li>
						<li>Charge it from your vehicle's 12V cigarette lighter socket</li>
						<li>Charge it from our EP-55 portable 55-watt solar panels (shown left)</li>
						<li>From our SunSocket Solar Generator</li>
					</ol> 
					
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
