<!--start homepage-->
    <div id="homepage" class="homepage section">
    
			
			<div class="energybar" id="html-content1">
					<ul class="slides">
						<?php /* <li><img src="<?php echo $this->getSkinUrl(); ?>images/sunsocket-solar-generator.png" alt="SunSocket Solar Generator" title="" /></li> */ ?>
						<li><img src="<?php echo $this->getSkinUrl(); ?>images/energybar.png" alt="Energybar" title="" /> </li>
					</ul>
                 </div>

			 <table id="wrappertable">
      <tr>
         <td>
			 <div class="home-title">
					
						<ul id="bxsliderCaption">
							<li class="captionSlide">
							
								<?php /*
								<h1>introducing</h1>
								<h2 style="color:#fadc5a;text-shadow:0px 1px 0px #c49802;">a new source of freedom</h2>
								*/ ?>
								<h1>make every day earth day</h1>
								<h2 style="color:#fadc5a;text-shadow:0px 1px 0px #c49802;">reduce your carbon footprint</h2>
								
							</li>
							
							<?php /*
							<li class="captionSlide">
								<h1>sunsocket solar generator</h1>
								<h2 style="padding-top:0px;margin-top:0px">
									<div class="actions">
								
									<a class="linkbutton learnmore brown" href="<?php echo $this->getUrl(); ?>shop/sunsocket-solar-generator.html"><span style="font-size:20px;text-shadow:none;color:#606163;">learn more</span></a>
							
									<div style="padding-top:10px;" class="price">
										<span style="margin-left:-18px;font-size:28px;color:#606163;text-shadow:none;">$1,999</span>
									</div>
								
									<div class="clearfix"></div>
									</div>
								</h2>
							</li>
							*/ ?>
							
							
						
						</ul>
					
				</div> 
				
				<?php /*
				<script type="text/javascript">
							jQuery(window).load(function() {
									jQuery('.slides').bxSlider({
									controls:false,
									pager: true,
									speed: 1000,
									
										onSlideBefore: function (currentSlideNumber, totalSlideQty, currentSlideHtmlObject) {
										jQuery('.active-caption').hide().removeClass('active-caption');
										jQuery('#bxsliderCaption>li').eq(currentSlideHtmlObject - 1).fadeIn(1000).addClass('active-caption')
										},
												onSliderLoad: function () {
											jQuery('#bxsliderCaption>li').eq(1).fadeIn(1000).addClass('active-caption')
										},
		   
		   
		   
									auto:true,
									pagerSelector: '#pager1',
									mode: 'fade',
									captions: false,
									 buildPager: function(slideIndex){
									  switch (slideIndex){
										case 0:
										  return '<div style="float:left;margin-right:5px" class="button" id="hpprev"></div>';
										case 1:
										  return '<div style="float:left" class="button" id="hpnext"></div>';
									  }
									}
									});
							});
				</script>
				*/ ?>
				
				<script type="text/javascript">
							jQuery(window).load(function() {
									jQuery('.slides').bxSlider({
									controls:false,
									pager: false,
									speed: 1000,
									
										onSlideBefore: function (currentSlideNumber, totalSlideQty, currentSlideHtmlObject) {
										jQuery('#bxsliderCaption>li').eq(currentSlideHtmlObject - 1).fadeIn(1000).addClass('active-caption')
										},
												onSliderLoad: function () {
											jQuery('#bxsliderCaption>li').eq(0).fadeIn(1000).addClass('active-caption')
										},
		   
		   
		   
									auto:false,
									pagerSelector: '#pager1',
									mode: 'fade',
									captions: false,
									 buildPager: function(slideIndex){
									  switch (slideIndex){
										case 0:
										  return '<div style="float:left;margin-right:5px" class="button" id="hpprev"></div>';
										case 1:
										  return '<div style="float:left" class="button" id="hpnext"></div>';
									  }
									}
									});
									
									jQuery(".teaser").css({backgroundSize: "cover"});
							});
							
							
				</script>
				
				
				
				
			
			<div id="pager1">
			
			<div id="hpprev"></div>
			<div id="hpnext"></div>
			</div>
		 
			<div style="text-align:center;" id="scrollbutton">
                         <a class="navigateTo" href="#energybarinfo"></a> 
            </div>
		</td>
      </tr>
   </table>
		
		
		<img onclick="location.href='<?php echo $this->getUrl(); ?>shop.html';" style="cursor:pointer;z-index:9999;position:absolute;bottom:0px;right:0px;" src="<?php echo $this->getSkinUrl(); ?>images/specialgraphic-free-shipping.png" alt="Special" title="" /> 	 

      </div>
	 <!--end homepage-->

	 <!---- ENERGYBAR INFO -->
	 
	 
     <div id="energybarinfo" class="page odd section">
        
      
        <div class="content clearfix">
        
			
				<div style="width:617px;margin-right:10px;padding-right:0px;height:500px;display:block;" class="column_one_half">
				</div>
				
			
			
            <div style="width:510px;" class="column_one_half last">
				<div style="width:505px; " class="energybartext">
					<h1 class="pirulen">EnergyBar<span style="font-weight:bold;font-family:Century Gothic;font-size:12px;position: relative; bottom: 3.5ex;">TM</span> 250</h1>
						
						<strong>2.0 x 16.5 x 6.3 in.  |  8 lbs.</strong>
						
						<p class="sinfo">The EnergyBar 250 contains massive portable power that can be charged from solar panels, solar generators, wall sockets, and car lighter adapters.</p>
						
						<div class="column_one_half">
							<h2>overview</h2>
							<p>The lightest high-capacity battery pack available. Stop searching for outlets; bring your own.</p>
							<p>Discover the freedom to roam with portable power that fits in your backpack, overhead compartment, or with your gear. Power domestic or international electronic equipment up to 100 watts with the universal AC outlet, 12V lighter socket, or four USB sockets.</p>
						</div>
						
						<div class="column_one_half last">
							<h2>how it works</h2>
							<p style="overflow: visible !important; ">The EnergyBar 250 uses advanced Lithium Iron Phosphate (LiFePO4) battery technology, and is three times lighter and lasts twice as long as an equivalent lead-acid battery.</p>
							
							<p>The 20Ah (250Wh) battery can sit idle for years and only self-discharge at a minor 0-2% power per month, making it ideal for anyone from the weekend camper to the outdoors professional.</p>
						</div>
						
						<div class="clearfix"></div>
						
						<div class="actions">
							
								<a style="margin-left:20px;" class="linkbutton learnmore" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>learn more</span></a>
						
							
							
								<a class="linkbutton buyitnow" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>buy it now</span></a>
						
							
								<?php /*
								<div style="margin-left:25px;" class="price">
									<span>$499</span>
								</div>
								*/ ?>
							
						</div>
				</div>
          </div>
		  
		   
	
		  
   	   </div>
       
		
		 
			 
	 

     </div>
	 
	 <div id="teaser-1" class="teaser" style="background-image: url(<?php echo $this->getSkinUrl(); ?>images/bkg2.jpg);">
         </div>
<!--end energybarinfo content-->
      
     
	
	 
	 
	 
	 
<div id="products3" class="page odd section">  
	<div style="padding-bottom:0px !important" class="content"> 

		
			<div style="margin-bottom:0px" class="column_one_third product product1">
				<div class="pcontent">
					<h3 class="pirulen"><span style="font-size:32px;">S</span>un<span style="font-size:32px;">S</span>ocket</h3>
					<h4 class="pirulen">solar generator</h4>
					<div class="image">
					<img src="<?php echo $this->getSkinUrl(); ?>images/product-sunsocket.jpg" alt="SunSocket Solar Generator" />
					</div>					
				</div>
			</div>
			
			<div style="margin-bottom:0px" class="column_one_fourth product product2 ">	
				<div class="pcontent">
					<h3 class="pirulen">duo-flex</h3>
					<h4 style="line-height:20px;" class="pirulen">solar panel<br/>+ battery</h4>
					<div class="image">
					<img style="margin-top:-10px;" src="<?php echo $this->getSkinUrl(); ?>images/product-duo-flex-hp.jpg" alt="Duo-Flex Solar Panel + Battery" /> 
					</div>
				</div>
			</div>
			
			<div style="margin-bottom:0px" class="column_one_third last product product3">
				<div class="pcontent">
					<h3 class="pirulen"><span style="font-size:32px;">E</span>nergy<span style="font-size:32px;">B</span>ar 250</h3>
					<h4 class="pirulen">battery pack</h4>
					<div class="image">
					<img src="<?php echo $this->getSkinUrl(); ?>images/product-energybar250.jpg" alt="EnergyBar 250 Solar Battery Pack" /> 
					</div>
				</div>
			</div>
			
			<div class="clear"></div>


	</div>
	
	<div id="teaser-2" class="teaser fixed" style="background-image: url(<?php echo $this->getSkinUrl(); ?>images/bkg3.jpg);">
	
		<div style="position:relative;z-index:9999;" class="content"> 
				<div style="position:absolute;top:0px;height:265px;width:10000px;z-index:9999;background:#fff;right:1100px;"></div>
				<div style="position:absolute;top:0px;height:265px;width:10000px;z-index:9999;background:#fff;left:1100px;"></div>
					<div style="margin-top:0px" class="column_one_third product product1">
						<div style="padding-right:0px !important;padding-top:0px !important;background:none !important;" class="pcontent">
							<div class="circle circle1 transp">
								<div onclick="setLocation('<?php echo $this->getUrl(); ?>shop/sunsocket-solar-generator.html')" class="inner">
									<div class="actions">
										<a class="linkbutton learnmore" href="<?php echo $this->getUrl(); ?>shop/sunsocket-solar-generator.html"><span>learn more</span></a>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div style="margin-top:0px" class="column_one_third product product2">
						<div style="padding-right:0px !important;padding-left:0px !important;padding-top:0px !important;background:none !important;" class="pcontent">
							<div class="circle circle2 transp">
								<div onclick="setLocation('<?php echo $this->getUrl(); ?>shop/sunsocket-duo-flex.html')" class="inner">
									<div class="actions">
										<a class="linkbutton learnmore" href="<?php echo $this->getUrl(); ?>shop/sunsocket-duo-flex.html"><span>learn more</span></a>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div style="margin-top:0px" class="column_one_third product product3">
						<div style="padding-right:0px !important;padding-left:0px !important;background:none !important;" class="pcontent">
							<div class="circle circle3 transp">
								<div onclick="setLocation('<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html')" class="inner">
									<div class="actions">
										<a class="linkbutton learnmore" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>learn more</span></a>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div class="clear"></div>
		</div>
    </div>

</div>






 
	 
	 
<!-- start aboutus --> 
     <div id="aboutus" class="page odd section">
 
        <div class="content clearfix">
			<div class="column_one_third aspectlogo">
				<img src="<?php echo $this->getSkinUrl(); ?>images/aspect-solar-logo2.png" alt="Aspect Solar" />
			</div>
			
			<div class="column_two_thirds last abouttext">
				<div class="abouttextc">
					<p><span class="mediumstrong">Smart enough to bring technology along for the ride,</span><br/>and not let it get in the way.</span></p>
					
					<p class="small">AspectSolar is a pioneer of portable solar energy products, providing lifestyle solutions to the rest of the pioneers out there. Our products help people stay connected while getting away. Everything warmed by the light of the sun was put here for us to explore. AspectSolar supports the pioneers, the nomads, and the discoverers by removing the boundaries that keep them from going further.</p>
					
					<div class="actions">
						<a class="linkbutton learnmore" href="<?php echo $this->getUrl(); ?>learn/how-it-works"><span>learn more</span></a>
					</div>
				</div>
			</div>
			
			<div class="clear"></div>
			
			<div class="videos">
				<div class="column_one_third video video1">
					<a class="fancyboxvideo iframe" href="http://www.youtube.com/embed/qEFzyVTCibY"><img src="<?php echo $this->getSkinUrl(); ?>images/video1.jpg" alt="energybar features" /></a>
					<a class="videoview fancyboxvideo iframe" href="http://www.youtube.com/embed/qEFzyVTCibY"><span>EnergyBar 250</span></a>
					<a class="playbutton fancyboxvideo iframe" href="http://www.youtube.com/embed/qEFzyVTCibY"></a>
				</div>
				
				<div class="column_one_third video video2">
					<a class="fancyboxvideo iframe" href="http://www.youtube.com/embed/LpEAIBFIm9E"><img src="<?php echo $this->getSkinUrl(); ?>images/video2.jpg" alt="sunsocket in action" /></a>
					<a class="videoview fancyboxvideo iframe" href="http://www.youtube.com/embed/LpEAIBFIm9E"><span>Sun-tracking Technology</span></a>
					<a class="playbutton fancyboxvideo iframe" href="http://www.youtube.com/embed/LpEAIBFIm9E"></a>
				</div>
				
				<div class="column_one_third last video video3">
					<a class="fancyboxvideo iframe" href="http://www.youtube.com/embed/P1umuZfFMkk#t=132"><img src="<?php echo $this->getSkinUrl(); ?>images/video3.jpg" alt="our energy bar in action" /></a>
					<a class="videoview fancyboxvideo iframe" href="http://www.youtube.com/embed/P1umuZfFMkk#t=132"><span>The EnergyBar 250 in Action</span></a>
					<a class="playbutton fancyboxvideo iframe" href="http://www.youtube.com/embed/P1umuZfFMkk#t=132"></a>
				</div>
				
				<div class="clear"></div>
			</div>
			
			<div class="abouttitle">
				<h2>freedom is being fully <span class="yellow">charged</span></h2>
			</div>
        	
            
     	</div>    
        
     </div>
<!-- end aboutus --> 
    
    


    <div id="teaser-3" class="teaser" style="background-image: url(<?php echo $this->getSkinUrl(); ?>images/bkg4.jpg);">
	
	 <div id="footervid" class="page" style="height:auto">
		 <div class="content clearfix">
				<div class="videos">
					
			
				<?php 
					print $this->getLayout()
					 ->createBlock("wordpress/sidebar_widget_posts")
					 ->setTemplate("wordpress/sidebar/widget/posts-homepage.phtml")
					 ->toHtml(); 
				 ?>
			
				
					
					<div class="clear"></div>
				</div>
		 </div>
		
	 
	 </div>
	 
	 
     </div>