

<div class="inner-fullwidth">
	<div class="title">
		<h2>CPAP</h2>
		
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_social_icons')->toHtml() ?>
	</div>
	
	<div class="contentbox cpap">
		<div class="frdcont">
			<img src="<?php echo $this->getSkinUrl(); ?>images/energybar.jpg" alt="" title="" />
		
			<h1 class="frdh1">Freedom to Breathe. Power your CPAP device for all-day power and go where you want to, without limitations.</h1>
			
			<h1 class="pirulen">The EnergyBar&trade; 250</h1>
			
			<div class="frdaction">
				<a class="linkbutton learnmore black" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>learn more</span></a>
				<a class="linkbutton buyitnow" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>buy it now</span></a>
			</div>
			
			
			
			<p class="textpar">Don't worry about finding an outlet; bring along all the power you need in only 8 pounds. The EnergyBar 250 is one of the most powerful and portable battery packs in the world, featuring multiple outputs for all of your devices. Combined with our EP-55 portable solar panels, CPAP owners can enjoy <span style="font-weight:bold">unlimited multi-night power</span> anywhere in the world.</p>
			
			
			<h5>How long will the EnergyBar 250 power your CPAP?</h5>
			
			<table class="cpaptable" style="text-align:center">
				<tr>
					<td>
					&nbsp;
					</td>
					
					<td style="border-left:1px solid #e1e1e1;border-right:1px solid #e1e1e1;font-weight:bold;color:#da9a00;font-size:14px;">
					Average CPAP<br/>Power Consumption
					</td>
				
					<td style="border-right:1px solid #e1e1e1;font-weight:bold;color:#da9a00;font-size:14px;">
					Estimated<br/>Hours of Power
					</td>
					
					<td style="font-weight:bold;color:#da9a00;font-size:14px;" ROWSPAN=3>
					<div style="margin-bottom:38px;">With EP-55<br/>Solar Panels</div><span style="color:#606163;font-weight:bold;font-size:14px;">Full Recharge<br/>Everyday!</span>
					</td>

				</tr>

				
				<tr style="border-bottom:1px solid #e1e1e1">
					<td style="text-align:left;font-size:19px;font-weight:bold;color:#606163;border-right:1px solid #e1e1e1">
					No Humidifier
					</td>
					
					<td style="color:#da9a00;font-size:30px;font-weight:bold;border-right:1px solid #e1e1e1">
					10W
					</td>
				
					<td style="color:#da9a00;font-size:30px;font-weight:bold;border-right:1px solid #e1e1e1">
					24 Hours
					</td>

				</tr>
			

			<tr>
					<td style="text-align:left;font-size:19px;font-weight:bold;color:#606163;border-right:1px solid #e1e1e1">
					With Humidifier
					</td>
					
					<td style="color:#da9a00;font-size:30px;font-weight:bold;border-right:1px solid #e1e1e1">
					40W
					</td>
				
					<td style="color:#da9a00;font-size:30px;font-weight:bold;border-right:1px solid #e1e1e1">
					6 Hours
					</td>

				</tr>
			
			
			</table>
			
			<?php /*
			<h1 class="frdh2">freedom is being fully <span class="yellow">charged</span></h1>
				
				
			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img1.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>Travel with it</h5>
					
					<p>The EnergyBar 250 is ultra slim and fits in your suitcase. Weighing slightly less than 8 pounds and providing hours and hours of power, this portable unit will easily become one of your best travel buddies. Recharge it in 5 hours at your hotel or any wall outlet.</p>
				</div>
			</div>
			
			<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img4.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>CAMP WITH IT</h5>
					
					<p>This portable battery pack holds 250 watt hours of power, which is enough power for you to run anything from camping lights, small fans, radios, or even a television. We aren't exactly saying you should bring a TV every time you go camping, but you could!</p>
				</div>
			</div>
			
		
			
			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img5.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>TAILGATE WITH IT</h5>
					
					<p>You may not want to bring your television or laptop when you go camping, but why not when you go tailgating? Power your television, radios, phones, tablets, all from the convenience of the EnergyBar 250 battery pack!</p>
				</div>
			</div>
			
			<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img6.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>RECHARGE IT!</h5>
					
					<p>The EnergyBar 250 is truly the most versatile battery pack out there. You can recharge it multiple ways.
					
					<ol class="numbered">
						<li>Charge it from a wall outlet</li>
						<li>Charge it from your vehicle's 12V cigarette lighter socket</li>
						<li>Charge it from our EP-55 portable 55-watt solar panels (shown left)</li>
						<li>From our SunSocket Solar Generator</li>
					</ol> 
					
					</p>
				</div>
			</div>
			
			*/ ?>
		</div>
	</div>
</div>
