

<div class="inner-fullwidth">
	<div class="title">
		<h2>Aviation</h2>
		
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_social_icons')->toHtml() ?>
	</div>
	
	<div class="contentbox aviation">
		<div class="frdcont">
			<img src="<?php echo $this->getSkinUrl(); ?>images/energybar.jpg" alt="" title="" />
		
			<h1 class="frdh1">Freedom to Fly. Power your in-flight GPS or tablet from our 250Wh LFP battery for 12-25 hours.</h1>
			
			<h1 class="pirulen">The EnergyBar&trade; 250</h1>
			
			
			<div class="frdaction">
				<a class="linkbutton learnmore black" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>learn more</span></a>
				<a class="linkbutton buyitnow" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>buy it now</span></a>
			</div>
			
			<iframe style="margin-bottom:71px;" width="480" height="317" src="//www.youtube.com/embed/gsxMOVLjeGA?wmode=transparent" frameborder="0" allowfullscreen></iframe>
			
		
			
			<h1 class="frdh2">freedom is being fully <span class="yellow">charged</span></h1>
				

			<div class="aviationgridleft">
			<p style="line-height:22px;font-size:19px;color:#606163">The most powerful and most lightweight battery you can get for your aircraft. The fully charged EnergyBar 250 can power GPS and tablets alone for 12-25 hours, depending on the wattage. AspectSolar is a personal solar power company and the EnergyBar 250 was designed to be charged with solar panels (we recommend the EP-55). Charge the battery with solar panels or by plugging it in to a wall outlet; either way you're not using precious fuel to power your devices. Fly safer, fly farther, fly free.</p>
			
		
					
					<ol class="numbered bigger">
							<li><span style="font-weight:bold">Features 4 USB 2A outputs</span>. Power or charge up to 4 iPads, Garmins, or smartphones simultaneously at full speed. Charge your devices as fast as powering from a wall outlet.</li>
							<li>The EnergyBar 250 uses <span style="font-weight:bold">Lithium Iron Phosphate</span> battery technology, which is stable and non-hazardous (unlike other lithium-ions). And with no thermal runoff, your EnergyBar 250 won't overheat. Our battery pack also has a shelf-life of up to 10 years, making it the most reliable portable power solution ever.</li>
							<li><span style="font-weight:bold">250Wh of power</span> (20Ah) and it only weighs <span style="font-weight:bold">8 pounds</span>. Power your electronic devices from the Universal AC output, 12V DC output, or 4 USB 2A outputs! Versatility of this battery pack gives pilots the freedom to charge a wide variety of devices anywhere.</li>
							<li>Flying in Oshkosh? Charge the EnergyBar 250 directly from the EP-55 portable solar panels to give you unlimited power every day with sunlight. Or plug in to a wall outlet or 12V adapter in your car or aircraft.</li>
							<li>At only <span style="font-weight:bold">2 inches thick</span>, this high capacity energy source will fit virtually anywhere!</li>
						</ol> 

			
			</div>
			
			<div class="aviationgridright">
			
				<?php /*
				<div class="freedomgrid last">
				
					
					<div class="gridimg">
						<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img6.jpg" alt="" title="" />
					</div>
					
					<div class="divcnt">
						<h5>RECHARGE IT!</h5>
						
						<p>The EnergyBar 250 is truly the most versatile battery pack out there. You can recharge it multiple ways.
						
						<ol class="numbered">
							<li>Charge it from a wall outlet</li>
							<li>Charge it from your vehicle's 12V cigarette lighter socket</li>
							<li>Charge it from our EP-55 portable 55-watt solar panels (shown left)</li>
							<li>From our SunSocket Solar Generator</li>
						</ol> 
						
						</p>
					</div>
					
				</div>
				*/ ?>
				
				
				<p>
				<img src="<?php echo $this->getSkinUrl(); ?>images/aviationimg1.jpg" alt="" title="" />
				</p>
				
				<p style="font-size:14px;color:#606163;"><span style="font-weight:bold">Power Your</span> GPS, air cooler, radios or stereos, camping gear, tablet, trickle charger, CPAP, television, laptop, phone, SLR camera batteries, and more.</p>
				
				<p>
				<img src="<?php echo $this->getSkinUrl(); ?>images/aviationimg2.jpg" alt="" title="" />
				</p>
			
			
			
			</div>
			
			<div class="clear"></div>
		</div>
	</div>
</div>
