<div class="page-title">

		<h1>learn</h1>
</div>
	


<div class="inner-left">
	<div class="title"><h2>How Does A Solar Generator Work?</h2></div>
	<div class="contentbox">

			<h3>IN A NUT SHELL:</h3>
			<p>Photovoltaic cells aka "PV cells" aka "solar cells" convert the energy from the sun into what we all commonly refer to as electricity.  These cells are made of something called silicon, which is a semi-conductor.  When the suns rays hit the solar cells, the energy is transferred from photons to loose electrons.  An electric field forces these electrons to flow in a direction called a current.  </p>
			
			<div class="column_one_third">
				<div class="column1">
					<div class="imgicon">
					<img src="<?php echo $this->getSkinUrl(); ?>images/how-it-works-icon1.png" alt="" title="" />    
					</div>			
					<h4 class="style1">Solar panels track the sun</h4>
				</div>
			</div>
			
			<div class="column_one_third">
				<div class="column2">
					<div class="imgicon">
					<img src="<?php echo $this->getSkinUrl(); ?>images/how-it-works-icon2.png" alt="" title="" /> 
					</div>
					<h4 class="style1">Electricity is stored</h4>			
				</div>
			</div>
			
			<div class="column_one_third last">
				<div class="column3">
					<div class="imgicon">
					<img src="<?php echo $this->getSkinUrl(); ?>images/how-it-works-icon3.png" alt="" title="" />
					</div>
					<h4 class="style1">Power your electronic devices</h4>			
				</div>
			</div>
			
			<div class="clear"></div>
			
			<p>We can draw this current by placing metal contacts on each side of the solar cell.   We then feed this electrical current directly to a battery to store the energy so that you can power or charge your electronic devices.  This whole process is what makes up a "solar generator."  Our SunSocket&#0153;  solar generator takes it one step further by utilizing a proprietary sun-tracking system, which orients our solar cells to face directly to the sun,which maximizes the amount of energy converted from the sun throughout the day.</p>
		
		
		<h3>BIGGER BATTERY <img src="<?php echo $this->getSkinUrl(); ?>images/text-notequal.gif" alt="" title="" />  MORE POWER.</h3>
		
		<p>A solar generator is like a bucket of water with a tap.  The water is the energy collected from sunlight.  If the amount of energy collected from the sun is less than the amount of energy that is used to power your electronic devices, then you will run out of energy!  It doesn't matter how big the battery is in your solar generator if there isn't enough energy to keep the battery charged.  </p>
		
		<img class="floatleft" src="<?php echo $this->getSkinUrl(); ?>images/water-energy-info.jpg" alt="" title="" />
		<div style="float:left;margin-left:auto">
			<h3>THE POWER IS IN THE SOLAR PANELS</h3>
			<p style="width:348px;">The more energy that is being collected from the sun and converted to electricity, the longer the battery in your solar generator will stay charged.  With no new energy being collected, your battery becomes a paper weight.  </p>
			
			<h4 class="boldgray">Powering a 50-Watt Laptop:</h4>
			<p><span style="line-height:22px;color:#606163;font-weight:bold;">500Wh Battery and a 10-Watt PV Panel, 500Wh / (50W-10W) = 12.5 Hours</span><br/>
			<span style="line-height:22px;color:#279dff;font-weight:bold;">250Wh Battery and a 40-Watt PV Panel, 250Wh / (50W-40W) = 25 Hours</span>
			</p>
			<p style="margin-top:-3px;"><span style="color:#606163;font-weight:bold;">Conclusion?  More PV = More Power</span></p>
			
		</div>
		
		<div class="clear"></div>
		
		<h3 class="grey-23">Best technology available:</h3>
		
		<div class="floatlefticon">
		<img src="<?php echo $this->getSkinUrl(); ?>images/icon-sun-track.jpg" alt="" title="" />
		</div>
		<h3>Sun Tracking Technology</h3>
		<p>Solar panels must face directly towards the sun in order to collect efficient and substantial power. Without sun-tracking panels, you might never get enough sunlight to charge your batteries or devices. Imagine you are camping, and you want to leave your campsite to go fishing or hiking. You might be gone for about 5 hours, maybe even more.<br/><br/>
		
		The sun can move a lot in 5-7 hours. When you eventually get back to your campsite, regular solar panels will no longer be facing the sun, and therefore will not be collecting any power.  They become paperweights.  Sun-tracking technology means that you never have to worry about losing power.  You can leave your campsite all day and come back to a nice cold drink from your portable electric cooler.</p>
		
		<div class="box1">
			<div class="box1content">
				<div class="box1left">
					<h4 class="boldgray">Benefit:</h4>
					<ul class="line">
						<li>Maximizes the amount of sun energy converted<br/>into electricity</li>
						<li>Consistent charge throughout the day</li>
						<li>Optimizes the use of photovoltaic cells</li>
					</ul>
				</div>
				
				<div class="box1right">
					<h4 class="boldgray">Advantages:</h4>
					<ul class="line">
						<li>Never have to reposition the solar panels every time<br/>the sun moves</li>
						<li>Great for long-term needs spanning multiple days</li>
					</ul>
				</div>
				
				<div class="clear"></div>
			</div>
		</div>
		
		
		
		
		
		
		
		
		
		
		
		
		<div class="floatlefticon">
		<img src="<?php echo $this->getSkinUrl(); ?>images/icon-mono.jpg" alt="" title="" />
		</div>
		<h3>Mono-crystalline Solar Cells</h3>
		<p>Our solar cells are mono-crystalline which have the highest efficiency compared to poly-crystalline and thin-film technology. As technology continues to advance, you will see efficiency ratings get higher over time. Our SunSocket solar generators use solar panels rated at 60 Watts. The term "Rated" refers to the actual amount of watts that solar cell manufacturers get on the bare cell uncovered by any plastic or glass materials.</p>
		<p>Unfortunately, solar cells are quite fragile and need to be protected by such transparent material, which then slightly reduces the efficiency. Our panels, however, always get consistent high efficiency because they continuously are oriented towards the sun.</p>

		
		<div class="box1">
			<div class="box1content">
				<div class="box1left">
					<h4 class="boldgray">Benefit:</h4>
					<ul class="line">
						<li>Fast charging</li>
						<li>More power in less space</li>
					</ul>
				</div>
				
				<div class="box1right">
					<h4 class="boldgray">Advantages:</h4>
					<ul class="line">
						<li>Most efficient solar cell technology available</li>
					</ul>
				</div>
				
				<div class="clear"></div>
			</div>
		</div>
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		<div class="floatlefticon">
		<img src="<?php echo $this->getSkinUrl(); ?>images/icon-12v.jpg" alt="" title="" />
		</div>
		<h3>12.8V 20AH LiFePO4 Battery</h3>
		<p>There are many different types of batteries available on the market. We use lithium iron phosphate "LiFePO4" which is the best portable battery available at the moment. Lead-acid batteries are quite common in portable solar solutions and are also cheaper.Unfortunately these batteries are also very heavy. For example, a 250Wh lead-acid battery might weigh up to 18 pounds.</p>

<p>Our entire SunSocket solar generator, which has built in solar panels, a 250Wh LiFePO4 battery as well as a hard metal case, has a combined weight of only 25 pounds. The downside is that lithium iron phosphate is much more expensive than the common lead-acid, but it is worth it. They also have a much longer life span compared to other lithium ion batteries.</p>
		
		<div class="box1">
			<div class="box1content">
				<div class="box1left">
					<h4 class="boldgray">Benefit:</h4>
					<ul class="line">
						<li>Long life span, only drops 2% per month when not<br/>in use</li>
						<li>Can be recharged thousands of times</li>
					</ul>
				</div>
				
				<div class="box1right">
					<h4 class="boldgray">Advantages:</h4>
					<ul class="line">
						<li>Extremely lightweight increases portability</li>
						<li>Can be stored for an extended period of time</li>
					</ul>
				</div>
				
				<div class="clear"></div>
			</div>
		</div>
		


	</div>
</div>
