


<?php
// some helpers
$_helper = $this->helper('catalog/output');
$storeId = Mage::app()->getStore()->getId();
$catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);

// get all products that are marked as featured
$collection = Mage::getModel('catalog/product')->getCollection();

/*
$collection->addAttributeToSelect('featured');
$collection->addFieldToFilter(array(
array('attribute' => 'featured', 'eq' => true),
));
*/

// if no products are currently featured, display some text
?>

<div id="featured">
<div class="category-products">

<?php

$_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load(3);

?>


   <ul class="products-grid">
   
            <li style="width:325px;margin:0px 0px 0px 45px;padding:0px;border:none;" class="item">
				
				 <h2 class="product-name pirulen">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
					
						 <?php $_name2 = $_product->getResource()->getAttribute('name2')->getFrontend()->getValue($_product); ?>

						<p class="name1"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></p>
						<p class="name2"><?php echo $_name2; ?></p>
					</a>
				</h2>
				 
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
				<div onclick="setLocation('<?php echo $_product->getProductUrl() ?>')" class="itemhover"></div>
				<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(325,180); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
               
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="" class="linkbutton buyitnow"><span>learn more</span></a>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
					
					<div class="price-box">
					<?php echo Mage::helper('core')->currency($_product->getPrice()); ?>
					</div>
				
                </div>
				 
				<div class="clear"></div>
				
				 <div class="shortdesc">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                     
                 </div>
            </li>

        </ul>
  



      

</div>



</div>