

<div class="inner-left">
	<div class="title"><h2>freedom is being <span class="yellow">fully charged</span></h2></div>

	<div class="contentbox">
		<div class="frdcont">


			<div class="freedomgrid">
				<div class="gridimg">
					<a href="<?php echo $this->getUrl('freedom/aviation'); ?>"><img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img3.jpg" alt="solar generator" title="" /></a>
				</div>

				<div class="divcnt">
					<h5><a href="<?php echo $this->getUrl('freedom/aviation'); ?>">Freedom to Fly</a></h5>

					<p>The lightweight EnergyBar 250 is a Lithium Ion Phosphate battery, meaning that it still packs a massive punch. Power your tablet or GPS while you fly and still plug in a fan. Enjoy a new level of safety and comfort with solar technology. Bring an EP-55 into the wilderness to recharge your battery during travel.</p>
				</div>
			</div>




			<div class="freedomgrid last">
				<div class="gridimg">
					<a href="<?php echo $this->getUrl('freedom/travel-safely.html'); ?>"><img src="<?php echo $this->getSkinUrl(); ?>images/travel_safely-freedom.jpg" alt="" title="" /></a>
				</div>

				<div class="divcnt">
					<h5><a style="color:#f4c023;" href="<?php echo $this->getUrl('freedom/travel-safely.html'); ?>">Freedom to Travel</a></h5>


					<p>Harness the power of the sun, no matter where your adventures take you. Our LiFePO4 batteries are safe to take with you on the plane, in your checked baggage, or anywhere else you can pack it. Our technology ensures that there's no thermal runoff, no overheating, and have a low Equivalent Lithium Content - meaning they're permitted by the Department of Transportation!</p>
					<?php /*
					<br/>
					<p>
						<a href="<?php echo $this->getUrl(); ?>travel-safely.html">learn more</a>
					</p>
					*/ ?>
				</div>
			</div>









			<div class="freedomgrid">
				<div class="gridimg">
					<a href="<?php echo $this->getUrl('freedom/cpap'); ?>"><img src="<?php echo $this->getSkinUrl(); ?>images/freedom-to-breathe.jpg" alt="" title="" /></a>
				</div>

				<div class="divcnt">
					<h5><a href="<?php echo $this->getUrl('freedom/cpap'); ?>">Freedom to Breathe</a></h5>

					<p>Re-discover the freedom to move and live your life. Take all-day power along for the ride with the EnergyBar 250. Power your CPAP device without having to worry about if there will be an outlet or not. And at only 8 pounds of weight, this is the lightest and most powerful battery you could want.</p>
				</div>
			</div>





			<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img2.jpg" alt="solar power generators" title="solar powered generator" />
				</div>

				<div class="divcnt">
					<h5>Freedom to Sail</h5>

					<p>Use the unlimited power of the sun to solar power your electronic devices at sea and not precious fuel. The EnergyBar 250 is a powerful battery with 1 AC and 4 USB outlets. Both the battery and the EP-55 solar panels zip up in neoprene cases, making them weather- and splash-resistant. </p>
				</div>
			</div>






			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img1.jpg" alt="" title="" />
				</div>

				<div class="divcnt">
					<h5>Freedom to Move</h5>

					<p>Work can sometimes take you far away, but that doesn't mean work doesn't follow you. Stay connected with a full charge from the EnergyBar 250 or the freedom to work anywhere with an EP-55 and battery back. The world doesn't stop moving and neither should you. </p>
				</div>
			</div>



			<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img4.jpg" alt="portable solar panels" title="" />
				</div>

				<div class="divcnt">
					<h5>Freedom to Explore</h5>

					<p>This portable solar battery EnergyBar 250 battery pack holds 250 watt-hours of power, which is enough power for you to run anything from camping lights and small fans, to radios or even a television. The wilderness is there for you to discover, don't worry about running low on charge.  </p>
				</div>
			</div>








			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-to-play.jpg" alt="portable solar technology" title="solar powered portable generators" />
				</div>

				<div class="divcnt">
					<h5>Freedom to Play</h5>

					<p>Kids toys take power, and power isn't free. Except when it's from the sun. Enjoy unlimited solar power for smartphones using the DUO-Flex, extra battery for long car trips with the EnergyBar 250, or a magical movie night in the woods the kids will never forget with the SunSocket.</p>
				</div>
			</div>



		<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-is-being-fully-charged.jpg" alt="" title="" />
				</div>

				<div class="divcnt">
					<h5>Freedom is Being Fully Charged</h5>

					<p>Never run out of juice again on a shoot. Don't drag bags and bags of batteries along for the ride; bring one: the EnergyBar 250. The high-capacity back can keep charging and charging for hours. And when it runs down, power it up with a SunSocket or EP-55 for unlimited power. Capture every moment.</p>
                    <br>
                    <p><a href="<?php echo $this->getUrl('freedom/travel-safely.html') ?>">Travel Safely</a></p>

					</p>
				</div>
			</div>











			<div class="clear"></div>
		</div>
	</div>
</div>
