<div id="advantage" class="page odd section">
								 <div class="content clearfix">
								 
								 
								  <h2 style="margin-bottom:15px">The Aspect Advantage</h2>
								  
								  <p class="h3">Power - Portability - Safety - Value</p>
								  
								  <div class="cntn">
								  
								  <p class="whentext">When it comes to the most advanced solar technology for your life, look no further than AspectSolar. When we say: <strong>"Freedom is being fully charged"</strong>, it's not just a slogan - it's a way of life that powers everything we build. Which is why we take such pride in using only the highest quality parts, technology, and service for your solar charging needs.</p> 
								  

									<div id="tabbed-nav">
									  <ul>
										<li class="tab1"><a><span class="tabicon"></span><span class="tabtext">Green Battery</span></a></li>
										<li class="tab2"><a><span class="tabicon"></span><span class="tabtext">Sun Tracking Technology</span></a></li>
										<li class="tab3"><a><span class="tabicon"></span><span class="tabtext">Solar Panels</span></a></li>                           
										<li class="tab4"><a><span class="tabicon"></span><span class="tabtext">Portability Without Limitations</span></a></li>
									  </ul>
									  <div>
										<div>
											<h4>GREEN BATTERY TECHNOLOGY:</h4>
											<p>Safe, clean, and recycleable LiFePO4 and LiPO batteries power all our devices. These long lasting, cutting edge batteries will keep you fully charged for years to come.</p>
										</div>
										<div>
											<h4>SUN TRACKING TECHNOLOGY:</h4>
											<p>Our panels feature exclusive SolTrax<sup>TM </sup>and Maxiumum Power Point Tracking technology - allowing your solar panels to catch every solar ray, no matter where the sun is.</p>
										</div>
										<div>
											<h4>SOLAR PANELS:</h4>
											<p>Monocrystalline Solar Cells with up to 22% Efficiency Rating, and Monocrystalline Silicon Panels with 22% Efficiency Rating - double your standard solar panels!</p>			
										</div>
										<div>
											<h4>PORTABILITY WITHOUT LIMITATIONS:</h4>
											<p>AspectSolar products weigh up to 50% lighter than other products, and come ready to charge. Setup, plug in, and you've got the freedom to be fully charged in your hands!</p>			
										</div>         
									  </div>
									</div>

									

									<script> 
									jQuery(document).ready(function ($) {
										$("#tabbed-nav").zozoTabs({
											theme: "white",
											style: "clean",
											 mobileNav: false ,
											animation: {
												duration: 400,
												effects: "fade"
											}
										})
									});
									</script>

									</div>


								 
								 </div>


							</div>

		
					<div style="background:none !important;" class="page" id="howitworks">
						<div style="margin-top:30px !important" class="content cms"> 
							<div style="margin-left:90px;margin-right:90px;" class="contentbox">
										<h3 style="margin-bottom:50px;text-align:center;text-transform:none" class="grey-23">AspectSolar uses the most <span style="color:#f6c221;">advanced technology</span> available</h3>
										
										<div style="width:47%;" class="f-left">

												<div class="floatlefticon">
												<img src="<?php echo $this->getSkinUrl(); ?>images/icon-mono.jpg" alt="diy solar power" title="" />
												</div>
												<h3>Monocrystalline Solar Cells</h3>
												<p>These PV cells have the highest efficiency compared to polycrystalline and thin film cells. Monocrystalline can achieve 11-22% efficiency - almost double the range of what polycrystalline cells can produce. This is the <a href="<?php echo $this->getUrl(); ?>solar-power-pack-pro-60.html">most efficient solar cell available</a> for consumer products right now. We get excited about advances in solar technology, though; almost as excited as you get about new AspectSolar products. As more powerful technology becomes available, we'll roll out new releases to match.</p>

												
												<div class="box1">
													<div class="box1content">
													
													
														<div style="padding-left:5px;">
															<h4 class="boldgray">Benefit:</h4>
															<ul class="line">
																<li>19% Efficiency</li>
																<li>Quick charging</li>
																<li>More power, less space</li>
															</ul>
														</div>
														
														<hr style="height:0px;border-bottom:0px;border-top:1px solid #dddddd">
														
														<div style="padding-left:5px;">
															<h4 class="boldgray">Found in:</h4>
															<ul class="line">
																<li><a href="<?php echo $this->getUrl(); ?>products/ep-60-portable-solar-panels.html">EP-60</a>, <a href="<?php echo $this->getUrl(); ?>products/duo-flex-solar-charger.html">DUO-Flex</a>, <a href="<?php echo $this->getUrl(); ?>products/sunsocket-solar-generator.html">SunSocket Solar Generator</a></li>
															</ul>
															
														</div>
														
														<div class="clear"></div>
													</div>
												</div>
										
										
										
										</div>
										
										
										
										
										
										<div style="width:47%;" class="f-right">
											
										
											<div class="floatlefticon">
											<img src="<?php echo $this->getSkinUrl(); ?>images/icon-12v.jpg" alt="how does solar energy work" title="" />
											</div>
											<h3>LiFePO4 Battery</h3>
											<p>Batteries come in all shapes and sizes, but we use only the most efficient technology for our systems. A Lithium Iron Phosphate battery, or LiFePO4 for short, is the <a href="<?php echo $this->getUrl(); ?>energybar250-power-inverter-battery.html">best battery available for high-capacity portable needs</a>. Cheaper lead-acid batteries are very common in solar generator solutions, but they last half as long, are not as safe as LiFePO4s, and are much heavier. A 250Wh lead-acid battery may weigh up to 20 lbs. For truly portable solar technology, that's not acceptable. </p>
											
											<div class="box1">
												<div class="box1content">
												
													<div style="padding-left:5px;">
														<h4 class="boldgray">Benefit:</h4>
														<ul class="line">
															<li>Much lighter</li>
															<li>Double-to-triple the lifespan of lead-acid batteries</li>
															<li>0-2% discharge per month</li>
														</ul>
													</div>
													
													<hr style="height:0px;border-bottom:0px;border-top:1px solid #dddddd">
													
													<div style="padding-left:5px;">
														<h4 class="boldgray">Found in:</h4>
														<ul class="line">
															<li><a href="<?php echo $this->getUrl(); ?>products/energybar250-power-inverter-battery.html">EnergyBar250</a>, <a href="<?php echo $this->getUrl(); ?>products/sunsocket-solar-generator.html">SunSocket Solar Generator</a></li>
														</ul>
													</div>
													
													<div class="clear"></div>
												</div>
											</div>
										
										</div>
										
										
										<div style="padding:35px 0px;" class="clear"></div>
										
										<div style="width:47%;" class="f-left">
										
										
											<div class="floatlefticon">
											<img style="margin-top:-25px;" src="<?php echo $this->getSkinUrl(); ?>images/icon-sun-track.jpg" alt="solar power how it works" title="" />
											</div>
											<h3>SOLTRAX&trade; Sun-Tracking Technology</h3>
											<p>The sun moves throughout the day, why shouldn't your <a href="<?php echo $this->getUrl(); ?>ep-60-portable-solar-panels.html">CES Innovation Award-winning</a> <a href="http://www.aspectsolar.com/sunsocket-solar-generator.html">SunSocket Solar Generator</a> will rotate the panels to follow the sun's path across the sky. You can go for an all-day hike and still come home to a fully charged battery.</p>
											
											<div class="box1">
												<div class="box1content">
													<div style="padding-left:5px;">
														<h4 class="boldgray">Benefit:</h4>
														<ul class="line">
															<li>Maximizes the amount of solar energy converted into electricity</li>
															<li>Requires less attention throughout the day</li>
															<li>Consistent charge</li>
														</ul>
													</div>
													
													<hr style="height:0px;border-bottom:0px;border-top:1px solid #dddddd">
													
													<div style="padding-left:5px;">
														<h4 class="boldgray">Found in:</h4>
														<ul class="line">
															<li><a href="<?php echo $this->getUrl(); ?>products/sunsocket-solar-generator.html">SunSocket Solar Generator</a></li>
														</ul>
													</div>
													
													<div class="clear"></div>
												</div>
											</div>
											
											
										</div>
										
										<div style="width:47%;" class="f-right">
										
										
											<div class="floatlefticon">
											<img style="margin-top:-25px;" src="<?php echo $this->getSkinUrl(); ?>images/icon-solmax.jpg" alt="solar power cost" title="portable solar power" />
											</div>

											<h3>Maximum Power Point Tracking Technology</h3>
											<p>Maximum Power Point Tracking (MPPT) regulates the electrical field within solar panels to ensure that a maximum charge is being drawn out at any given time. Environmental conditions like partial shade or inconsistent cloud cover hamper the electrical conversion process. With our technology, any slowdown is minimized. Our MPPT also includes an LED that lights up when the panels are angled in such a way to receive maximum light.</p>
											
											<div class="box1">
												<div class="box1content">
													<div style="padding-left:5px;">
														<h4 class="boldgray">Benefit:</h4>
														<ul class="line">
															<li>Regulates electrical conversion</li>
															<li>Charges more efficiently</li>
														</ul>
													</div>
													
													<hr style="height:0px;border-bottom:0px;border-top:1px solid #dddddd">
													
													<div style="padding-left:5px;">
														<h4 class="boldgray">Found in:</h4>
														<ul class="line">
															<li><a href="<?php echo $this->getUrl(); ?>products/ep-60-portable-solar-panels.html">EP-60</a></li>
														</ul>
													</div>
													
													<div class="clear"></div>
												</div>
											</div>
										
										</div>
										
										<div class="clear"></div>
							</div>
						</div>
					</div>