<div class="inner-fullwidth">
 
	<div class="title">
		<h1>partners</h1>
		
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_social_icons')->toHtml() ?>
	</div>
	
	<div class="contentbox">
		<h3>Beyond Skiing Everest</h3>

		<p>AspectSolar sponsors adventurers Mike and Steve Marolt, the 8000m (8K) descent skiers behind the 2009 documentary <a target="_blank" href="http://www.skiingeverest.net/">Skiing Everest</a>. After a tour of festivals, ESPN bought the film in 2011 for a series of primetime broadcasts. The brothers and their friend, Jim Gile, are gearing up for the follow-up series, Beyond Skiing Everest. To film their expeditions, the Skiing Everest team relies on the best equipment available for their movie, and for their survival. Naturally, the powerful lightweight batteries and portable solar panels of AspectSolar were the perfect fit.</p>

		<p>With temperatures plummeting below -50&#176;F in the winter, Mike searched for the most reliable heated in-soles and the best portable batteries to power them with. These are the "golden gadgets" - gear that puts the expedition's lofty goals safely within their reach. Along with powering their film equipment, an electrical source is needed to recharge the heated in-soles and fend off frostbite. AspectSolar is sponsoring the crew with two each of the EnergyBar 250 and EP-55 solar panels, all made with the same technology as their CES Innovation Award-winning SunSocket Solar Generator. Marolt's previous experience with solar power on an expedition involved heavy, cumbersome solar panels and inefficient car batteries.</p>

		<p>AspectSolar is helping the mountaineers reach more difficult heights in harsher conditions. New technology is making their trips safer and more efficient. We're helping these pioneers go further.</p> 


		<h3>Aircraft Spruce & Specialty Co.</h3>

		<p>For international shipping, AspectSolar partners with <a target="_blank" href="https://www.aircraftspruce.com/catalog/elpages/aspectsolar14.php">Aircraft Spruce</a>. As our exclusive international master distributor, their team is more than capable of answering all of your international shipping needs. They also handle sales for customers in Alaska and Hawaii. The team at Aircraft Spruce has been serving pilots and more around the world since 1965. Visit our shop on their site to place orders for delivery outside of the continental United States.</p>



	</div>
	
	
</div>

