

<div class="inner-fullwidth">
	<div class="title">
		<h2>Aviation</h2>
		
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_social_icons')->toHtml() ?>
	</div>
	
	<div class="contentbox aviation">
		<div class="frdcont">
			<img src="<?php echo $this->getSkinUrl(); ?>images/energybar.jpg" alt="" title="" />
		
			<h1 class="frdh1">Introducing the most light weight & powerful battery<br/>pack, as seen at the <span style="font-weight:bold;">AOPA Aviation Summit!</span></h1>
			
			<h1 class="pirulen">EnergyBar<span class="tm">TM</span> 250</h1>
			
			<div class="nowtakedate">* now take $100 off through november</div>
			
			<div class="frdaction">
				<a class="linkbutton learnmore black" href="<?php echo $this->getUrl(); ?>products/sunsocket-energybar-250.html"><span>learn more</span></a>
				<a class="linkbutton buyitnow" href="<?php echo $this->getUrl(); ?>products/sunsocket-energybar-250.html"><span>buy it now</span></a>
			</div>
			
			<iframe style="margin-bottom:71px;" width="480" height="317" src="//www.youtube.com/embed/gsxMOVLjeGA?wmode=transparent" frameborder="0" allowfullscreen></iframe>
			
		
			
			<h1 class="frdh2">freedom is being fully <span class="yellow">charged</span></h1>
				

			<div class="aviationgridleft">
			<p style="line-height:22px;font-size:19px;font-weight:bold;color:#606163">The first & only high capacity battery pack powerful enough to be classified as a "generator", and is extremely lightweight and safe for aircraft.</p>
			
			<h5>Why do pilots love it?</h5>
					
					
					<ol class="numbered bigger">
							<li>Features 4 USB 2.0A outputs! Power or charge up to 4 iPads, Garmins, or smart phones simultaneously at FULL SPEED. Charge your devices as fast as powering from a wall outlet.  </li>
							<li>The EnergyBar 250 uses lithium iron phosphate battery technology which is stable and non-hazardous (unlike other lithium-ions). There is NO THERMAL RUNOFF! No overheating! Our battery pack also has a very long shelf-life of up to 10 years, making it the most reliable portable power solution ever.</li>
							<li>250 watt hours of power (20Ah) and and only weighs 8 pounds! Power your electronic devices from the Universal AC output, 12V DC output, or 4 USB 2A outputs! Versatility of this battery pack gives pilots the freedom to charge a wide variety of devices anywhere</li>
							<li>Flying in Oshkosh? GREAT FOR CAMPING! Charge the EnergyBar 250 directly from our EP-55 Portable Solar Panels to give you unlimited power every day with sunlight!</li>
							<li>The EnergyBar is so compact. Only about 2 inches thick, this high capacity energy source will fit virtually anywhere!</li>
						</ol> 

			
			</div>
			
			<div class="aviationgridright">
			
				<div class="freedomgrid last">
					<div class="gridimg">
						<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img6.jpg" alt="" title="" />
					</div>
					
					<div class="divcnt">
						<h5>RECHARGE IT!</h5>
						
						<p>The EnergyBar 250 is truly the most versatile battery pack out there. You can recharge it multiple ways.
						
						<ol class="numbered">
							<li>Charge it from a wall outlet</li>
							<li>Charge it from your vehicle's 12V cigarette lighter socket</li>
							<li>Charge it from our EP-55 portable 55-watt solar panels (shown left)</li>
							<li>From our SunSocket Solar Generator</li>
						</ol> 
						
						</p>
					</div>
				</div>
				
				
				<p>
				<img src="<?php echo $this->getSkinUrl(); ?>images/aviationimg1.jpg" alt="" title="" />
				</p>
				
				<p style="font-size:14px;color:#606163;"><span style="font-weight:bold">Our Energybar250 powers</span> GPS, Air Coolers, Radios & Stereos, Camping Gear, Tablets, Trickle Chargers, CPAPS, Televisions, Laptops, Phones, SLR camera batteries & more!</p>
				
				<p>
				<img src="<?php echo $this->getSkinUrl(); ?>images/aviationimg2.jpg" alt="" title="" />
				</p>
			
			
			
			</div>
			
			<div class="clear"></div>
		</div>
	</div>
</div>
