<div class="page-title">

		<span class="cmstitle">how it works</span>
</div>
	


<div class="inner-left">
	<div class="title"><h1>how does <span style="color:#f6c221;">solar power</span> work?</h1></div>
	<div class="contentbox">
	
		 <h3>IN A NUT SHELL:</h3>
		 
		 <p>Photovoltaic cells aka "PV cells" aka "solar cells" convert the energy from the sun into what we all commonly refer to as electricity.  These cells are made of something called silicon, which is a semi-conductor.  When the suns rays hit the solar cells, the energy is transferred from photons to loose electrons.  An electric field forces these electrons to flow in a direction called a current.</p>
							
			
			<div class="column_one_third">
				<div class="column1">
					<div class="imgicon">
					<img src="<?php echo $this->getSkinUrl(); ?>images/how-it-works-icon1.png" alt="how does solar power work" title="" />    
					</div>			
					<h4 class="style1">Solar panels track the sun</h4>
				</div>
			</div>
			
			<div class="column_one_third">
				<div class="column2">
					<div class="imgicon">
					<img src="<?php echo $this->getSkinUrl(); ?>images/how-it-works-icon2.png" alt="how solar power works" title="" /> 
					</div>
					<h4 class="style1">Electricity is stored</h4>			
				</div>
			</div>
			
			<div class="column_one_third last">
				<div class="column3">
					<div class="imgicon">
					<img src="<?php echo $this->getSkinUrl(); ?>images/how-it-works-icon3.png" alt="solar power kits" title="" />
					</div>
					<h4 class="style1">Power your electronic devices</h4>			
				</div>
			</div>
			
			<div class="clear"></div>
			
			
			<p>We can draw this current by placing metal contacts on each side of the solar cell.   We then feed this electrical current directly to a battery to store the energy so that you can power or charge your electronic devices.  This whole process is what makes up a "solar generator."  Our SunSocket&trade; solar generator takes it one step further by utilizing a proprietary sun-tracking system, which orients our solar cells to face directly to the sun,which maximizes the amount of energy converted from the sun throughout the day.  </p>
			
			<h3>BIGGER BATTERY &ne; MORE POWER.</h3>
			<p>A solar generator is like a bucket of water with a tap.  The water is the energy collected from sunlight.  If the amount of energy collected from the sun is less than the amount of energy that is used to power your electronic devices, then you will run out of energy!  It doesn't matter how big the battery is in your solar generator if there isn't enough energy to keep the battery charged.</p>
			
			<?php /*
			<p>We can draw this current by placing metal contacts on each side of the solar cell.   We then feed this electrical current directly to a battery to store the energy so that you can power or charge your electronic devices.  This whole process is what makes up a "<a href="http://www.aspectsolar.com/sunsocket-solar-generator.html">solar generator</a>."  Our SunSocket&#0153;  solar generator takes it one step further by utilizing a proprietary sun-tracking system, which orients our solar cells to face directly to the sun,which maximizes the amount of energy converted from the sun throughout the day.</p>
		
		
		<h3>BIGGER BATTERY <img src="<?php echo $this->getSkinUrl(); ?>images/text-notequal.gif" alt="" title="" />  MORE POWER.</h3>
		
		<p>A <i>solar generator</a> is like a bucket of water with a tap.  The water is the energy collected from sunlight.  If the amount of energy collected from the sun is less than the amount of energy that is used to power your electronic devices, then you will run out of energy!  It doesn't matter how big the battery is in your solar generator if there isn't enough energy to keep the battery charged.  </p>
		
		<img class="floatleft" src="<?php echo $this->getSkinUrl(); ?>images/water-energy-info.jpg" alt="" title="" />
		<div style="float:left;margin-left:auto">
			<h3>THE POWER IS IN THE SOLAR PANELS</h3>
			<p style="width:348px;">The more energy that is being collected from the sun and converted to electricity, the longer the battery in your <i>solar generator</i> will stay charged.  With no new energy being collected, your battery becomes a paper weight.  </p>
			
			<h4 class="boldgray">Powering a 50-Watt Laptop:</h4>
			<p><span style="line-height:22px;color:#606163;font-weight:bold;">500Wh Battery and a 10-Watt PV Panel, 500Wh / (50W-10W) = 12.5 Hours</span><br/>
			<span style="line-height:22px;color:#279dff;font-weight:bold;">250Wh Battery and a 40-Watt PV Panel, 250Wh / (50W-40W) = 25 Hours</span>
			</p>
			<p style="margin-top:-3px;"><span style="color:#606163;font-weight:bold;">Conclusion?  More PV = More Power</span></p>
			
		</div>
		
		<div class="clear"></div>
		
		*/ ?>


	</div>
</div>
