<div class="inner-fullwidth">
 
	<div class="title">
		<h1>our story</h1>
		
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_social_icons')->toHtml() ?>
	</div>
	
	<div class="contentbox">
		<h3>AspectSolar: The Pioneers in Portable Solar Technology</h3>

		<p>No matter what you love to do - from wandering the great outdoors, to traveling the world, AspectSolar is portable power you passion. AspectSolar is the pioneer in portable solar energy, providing real solutions for a variety of applications and customers. </p>
	
<p>While most people associate solar electricity with large panels mounted on rooftops, AspectSolar's compact, modular solar electricity products provide real portable power solutions for even the most remote locations. Our solutions are lightweight, easy to carry, and fit perfectly to your lifestyle. Even our most powerful Solar Power Pro pack is lightweight, and easy to carry on all of your adventures.  </p>

<p>Our forward-thinking solar power products have not just earned high marks with our customers, but from major organizations as well. The AspectSolar SunSocket, the world's first and only sun-tracking portable solar generator, the most advanced portable solar generator in the world, earned honors as one of the best solar products at the 2014 International CES. And all of our full-size solar panels feature high-efficiency monocrystalline solar cells, and utilize our proprietary sun-tracking technology. This means your solar panels will always work with maximum efficiency.</p>

<p>AspectSolar products enable our customers to extend the use of their devices and power all the activities that drive their lives. No matter what you enjoy doing: camping, tailgating, boating, and much more, freedom is being fully charged.</p> 




	</div>
	
	
</div>

