<div class="page-title">

		 <span class="cmstitle">Sun Tracking</span>
</div>
	


<div class="inner-left">
	<div class="title">
	  <h1><span style="color:#f4c01f;">SOLTRAX&trade;</span> Sun-Tracking Technology</h1></div>
	<div class="contentbox">

			
			<p>The SunSocket is the first and only solar generator to use sun-tracking technology to optimize power output all day long. This technology allows your solar panels to automatically track sunlight and find the direction that the sun is shining from. For the maximum charge, solar panels should be perpendicular to the sun's rays. Panels that lay flat on the ground or a table will get light all day long, but they won't be making the most of it. Sun-tracking technology frees you to leave your panels behind and go for a hike, or a swim, or just a lunch break. Without any attention from you, they'll always find the highest intensity of light so you get the most power for your day.</p> 
			
			<p>For its sun-tracking ability, the <a href="<?php echo $this->getUrl(); ?>inspire/awards">CES Innovation Award-winning</a> honored the SunSocket Solar Generator in early 2014.</p>
			
			<iframe style="margin:25px 0px;" width="640" height="390" src="//www.youtube.com/embed/408ME2GapWg?wmode=transparent" frameborder="0" allowfullscreen></iframe>
		
			

	</div>
</div>
