<div class="page-title">

		<h1>learn</h1>
</div>
	


<div class="inner-left">
	<div class="title"><h2>Sun Tracking Technology</h2></div>
	<div class="contentbox">

			<h3>Our Solar-Tracking Technology is a proprietary technology which truly revolutionizes consumer solar products.</h3>
		
			<iframe style="margin:25px 0px;" width="640" height="390" src="//www.youtube.com/embed/408ME2GapWg?wmode=transparent" frameborder="0" allowfullscreen></iframe>
		
			<p>This technology allows the solar panels to automatically track the sunlight throughout the day. A common problem with current solar kits these days is that many users do not realize that solar panels need to face the sun to maximize their efficiency. If the sun moves behind the panels then their efficiency and power drop to almost zero. Even if the solar panels are placed flat on the ground or table, they will only provide power during the couple of hours that the sun is at it's peak position.</p>  

<p>Our solar-tracking technology removes this problem, and positions the panels to the location of the highest intensity from the sun so that you always know that you are getting the most power that you can get. Leave the SunSocket solar generator outside while you are camping, or at a picnic, and know that you never have move it.</p> 

	</div>
</div>
