<div class="page-title">

		<h1>learn</h1>
</div>
	


<div class="inner-left">
	<div class="title"><h2>Battery Types</h2></div>
	<div class="contentbox">

			<p>The battery is an essential part of a solar generator or even a small solar charger.  The battery is used to store power that is collected from the sun.  It is also a way to regulate the charge to your electronic devices ensuring that there is a consistent charge.  For example, if the sun becomes covered by clouds or even by an individual walking by, then the current drops immediately.  If there</p>
			
			<p>There are different types of batteries that are commonly used in portable electronic devices. Many solar generators or solar kits use a battery technology called <span style="font-size:12px;font-weight:bold;color:#606163;">Lead-Acid</span>. Other smaller devices widely use <span style="font-size:12px;font-weight:bold;color:#606163;">Lithium Polymer</span>.</p>
			
			<p>AspectSolar strives to provide only the best and most advanced technology available to our customers, which is called <span style="font-size:12px;font-weight:bold;color:#606163;">Lithium Iron Phosphate</span>. Here you can learn the basics about the common batteries found in portable devices. were no battery to store the power, then the charge to your electronic device would be interrupted.</p>
			
			<div class="table1">
                <table >
					 <tr>
						 <td class="blank">
							&nbsp;
                        </td>
                        <td class="tabletitlehighlight">
                            LiFePO4<br/>
							<span class="tabletitlesubw">(Lithium Iron Phosphate)</span>
                        </td>
                        <td style="border-left:none">
                            LiPo<br/>
							<span class="tabletitlesub">(Lithium Polymer)</span>
                        </td>
                        <td>
                            Lead Acid<br/>
							<span class="tabletitlesub">&nbsp;</span>
                        </td>
                    </tr>
					
                   
                    <tr>
						 <td class="col1">
							Average Weight
                        </td>
						
                        <td class="tabletdhighlight">
                            45 Wh / Pound
                        </td>
                        <td>
                            68 Wh / Pound
                        </td>
                        <td>
                            15Wh / Pound
                        </td>
                    </tr>
                    <tr>
						<td class="col1">
							General Size
                        </td>
						
                       <td class="tabletdhighlight">
                           Compact
                        </td>
                        <td>
                            Compact
                        </td>
                        <td>
                            Large
                        </td>
                    </tr>
                    <tr>
						 <td class="col1">
							Power to Weight Ratio
                        </td>
						
                       <td class="tabletdhighlight">
                            High
                        </td>
                        <td>
                            Very High
                        </td>
                        <td>
                            Very Low
                        </td>
                    </tr>
                    <tr>
						 <td class="col1">
							Stability
                        </td>
                       <td class="tabletdhighlight">
                            Very Safe & Stable
                        </td>
                        <td>
                            Hazardous
                        </td>
                        <td>
                           Very Safe
                        </td>
                    </tr>
					
					 <tr>
						 <td class="col1">
							Average Cycles
                        </td>
                       <td class="tabletdhighlight">
                            Over 1000
                        </td>
                        <td>
                            500 to 1000
                        </td>
                        <td>
                          About 500
                        </td>
                    </tr>
					
					 <tr>
						 <td class="col1">
							Self Discharge Rate
                        </td>
                       <td class="tabletdhighlight">
                            Less than 2% per month
                        </td>
                        <td>
                            5% per month
                        </td>
                        <td>
                          Up to 20% per month
                        </td>
                    </tr>
					
					 <tr>
						 <td class="col1">
							Life Span
                        </td>
                       <td class="tabletdhighlight">
                           Up to 10 Years
                        </td>
                        <td>
                           Up to 3 years
                        </td>
                        <td>
                          Up to 5 years
                        </td>
                    </tr>
                </table>
            </div>
			
			<h3>Benefits of LiFePO4 Batteries</h3>
			
			<p>LiFePO4 batteries are the best available portable battery solution on the market but not exactly the cheapest. AspectSolar is committed to providing their customers with only the best technology so all of our products use this particular battery. The power density is slightly lower than Lithium Polymer but still quite high which makes this type of battery compact and lightweight. It is also extremely stable, where as the LiPo battery has been known to explode or cause fires when not properly used or handled. Lead Acid batteries are the oldest and most common batteries currently found on the market, and are also quite reliable and cheap.</p>
			
				<p>The downside, though, is that Lead Acid batteries have an extremely low power density which makes the batteries very large and heavy and not suitable for portable applications. These Lead Acid batteries also have a very high self-discharge rate, which also makes them very unappealing for those looking for portable power since the batteries will completely die when sitting idle for too long. As you can see, while LiFePO4 batteries may not be the cheapest, they are truly the best and safest solution for any portable application especially portable solar generators.</p>
            

	</div>
</div>
