<div class="page-title">

		<h1>learn</h1>
</div>
	


<div class="inner-left">
	<div class="title"><h2>Battery Types</h2></div>
	<div class="contentbox">

			<p>Freedom is being fully charged, no matter where you are. Portability is important. Smartphones are powerful computers that take up less space than a wallet. You shouldn't have to trade wall sockets for heavy batteries. Our products primarily use Lithium Iron Phosphate (LiFePO4) batteries, which are three times lighter than traditional lead-acid. Small devices that use less power benefit from less efficient but more potent Lithium-ion Polymer batteries.</p>
			
			<div class="table1">
                <table >
					 <tr>
						 <td class="blank">
							&nbsp;
                        </td>
                        <td style="width:170px" class="tabletitlehighlight">
                            LiFePO4<br/>
							<span class="tabletitlesubw">(Lithium Iron Phosphate)</span>
                        </td>
                        <td style="border-left:none">
                            LiPo<br/>
							<span class="tabletitlesub">(Lithium-ion Polymer)</span>
                        </td>
                        <td>
                            Lead-Acid / SLA<br/>
							<span class="tabletitlesub">&nbsp;</span>
                        </td>
                    </tr>
					
                   
                    <tr>
						 <td class="col1">
							Power to Weight Ratio
                        </td>
						
                        <td class="tabletdhighlight">
                            45 Wh / Pound<br/>Light
                        </td>
                        <td>
                            68 Wh / Pound<br/>Lighter
                        </td>
                        <td>
                            15 Wh / Pound<br/>HEAVY
                        </td>
                    </tr>
                    <tr>
						<td class="col1">
							Size
                        </td>
						
                       <td class="tabletdhighlight">
                           Compact
                        </td>
                        <td>
                            Compact
                        </td>
                        <td>
                            Large
                        </td>
                    </tr>
                    <tr>
						 <td class="col1">
							Safety
                        </td>
						
                       <td class="tabletdhighlight">
                            Very Safe & Stable<br/>Safe Charging Non Toxic Chemistry
                        </td>
                        <td>
                            Safe in Smaller Formats<br/>Not as stable  Charge & <br/>Dis-Charge Sensitivity 
                        </td>
                        <td>
                           Safe if Handled Properly
                        </td>
                    </tr>
                    <tr>
						 <td class="col1">
							Average # of Cycles
                        </td>
                       <td class="tabletdhighlight">
                            1000-2000+
                        </td>
                        <td>
                           500-1000
                        </td>
                        <td>
                           200-300
                        </td>
                    </tr>
					
					 <tr>
						 <td class="col1">
							Self Discharge Rate
                        </td>
                       <td class="tabletdhighlight">
                            <2% per month
                        </td>
                        <td>
                           +-5% per month
                        </td>
                        <td>
                          Up to 30% per month
                        </td>
                    </tr>
					
					 <tr>
						 <td class="col1">
							Life Span
                        </td>
                       <td class="tabletdhighlight">
                            8-10 Years
                        </td>
                        <td>
                           2-4 Years
                        </td>
                        <td>
                          2-3 Years
                        </td>
                    </tr>
					
					 <tr>
						 <td class="col1">
							Green Factor
                        </td>
                       <td class="tabletdhighlight">
                            Environmentally Friendly<br/>Very Long Life  Contains NO acid or lead<br/>NO known carcinogens
                        </td>
                        <td>
                           Environmentally Friendly if disposed of properly<br/>Moderate Life<br/>Contains NO acid or lead           
                        </td>
                        <td>
                          Not Environmentally Friendly<br/>Very Short Life<br/>Highly Toxic Serious Pollutants
                        </td>
                    </tr>
					
				
                </table>
            </div>
			
			<h3>LiFePO4 Batteries</h3>
			<p>The first rechargeable battery invented in 1859 was a lead-acid battery. We've come a long way in the past 150 years. LiFePO4 batteries are a vast chemical improvement over their older counterpart. They are the safest, longest lasting, and lowest self-discharge rate available. This means portable power that lasts between weekend adventures, or even years without use. Plus, these batteries can take a beating without any risk of overheating, swelling, or chemical reactions. Phosphates are used as the cathode material and are stable in short circuit conditions, making LiFePO4 inherently superior to other Lithium-ion batteries.</p>
			
			<h3>Bigger Battery &ne; More Power</h3>
			<p>A solar generator is like a bucket of water with a tap. The water is the energy collected from sunlight. If the amount of energy collected from the sun is less than the amount of energy that is used to power your electronic devices, then you'll run out of power. It doesn't matter how big the battery is in your solar generator if there isn't enough energy to keep the battery charged; the power is in the solar panels. The more energy that is being collected from the sun and converted to electricity, the longer the battery in your solar generator will stay charged. With no new energy being collected, your battery becomes a paper weight.</p>
			
			<h4 class="boldgray">Powering a 50-Watt Laptop:</h4>
			
			<h5 style="font-size:14px"><span style="line-height:22px;font-weight:bold;color:#f4c023;">AspectSolar’s 250Wh LFP Battery 40W PV Panel</span> <span style="font-weight:bold">vs.</span> <span style="line-height:22px;font-weight:bold;color:#81acfb;">500Wh Battery + 10W PV Panel</span></h5>
			
			<p style="font-weight:bold"><span style="color:#81acfb;">500Wh</span> Battery and a <span style="color:#81acfb;">10-Watt</span> PV Panel, 500Wh / (50W-10W) = <span style="color:#81acfb;">12.5 Hours</span> of use<br/>
			<span style="color:#f4c023;">250Wh</span> Battery and a <span style="color:#f4c023;">40-Watt</span> PV Panel, 250Wh / (50W-40W) = <span style="color:#f4c023;">25.0 Hours</span> of use

			</p>
			<p style="margin-top:-3px;"><span style="color:#606163;font-weight:bold;">More PV = More Power</span></p>
			
			
            

	</div>
</div>
