

<div class="inner-fullwidth">
	<div class="title">
		<h2>&nbsp;</h2>
		
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_social_icons')->toHtml() ?>
	</div>
	
	<div class="contentbox">
		<div class="frdcont">
			<img src="<?php echo $this->getSkinUrl(); ?>images/energybar.jpg" alt="" title="" />
		
			<h1 class="frdh1">Power your lifestyle with the most versatile<br/>solar panels and battery packs on the market.</h1>
			
			<h1 class="pirulen">EnergyBar<span style="font-weight:bold;font-family:Century Gothic;font-size:12px;position: relative; bottom: 3.5ex;">TM</span> 250</h1>
			
			<div class="frdaction">
				<a class="linkbutton learnmore black" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>learn more</span></a>
				<a class="linkbutton buyitnow" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>buy it now</span></a>
			</div>
			
			<iframe style="margin-bottom:71px;" width="480" height="317" src="//www.youtube.com/embed/P1umuZfFMkk?wmode=transparent" frameborder="0" allowfullscreen></iframe>
			
			<h1 class="frdh2">freedom is being fully <span class="yellow">charged</span></h1>
			
			
			
			
			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img3.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>Freedom to Fly</h5>
					
					<p>The lightweight EnergyBar 250 is a Lithium Iron Phosphate battery, meaning that it still packs a punch. Power your tablet or GPS while you fly and still plug in a fan. Enjoy a new level of safety and comfort with solar technology. Bring an EP-55 into the wilderness to recharge your battery during travel.</p>
				</div>
			</div>
				
				
			
			
			<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img2.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>Freedom to Sail</h5>
					
					<p>Use the unlimited power of the sun to power your electronic devices at sea and not precious fuel. The EnergyBar 250 is a powerful battery with 1 AC and 4 USB outlets. Both the battery and the EP-55 solar panels zip up in neoprene cases, making them weather- and splash-resistant. </p>
				</div>
			</div>
			
			
			
			
			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img1.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>Freedom to Move</h5>
					
					<p>Work can sometimes take you far away, but that doesn't mean work doesn't follow you. Stay connected with a full charge from the EnergyBar 250 or the freedom to work anywhere with an EP-55 and battery back. The world doesn't stop moving and neither should you. </p>
				</div>
			</div>




			
			
			
			<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-img4.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>Freedom to Explore</h5>
					
					<p>This portable EnergyBar 250 battery pack holds 250 watt-hours of power, which is enough power for you to run anything from camping lights and small fans, to radios or even a television. The wilderness is there for you to discover, don't worry about running low on charge.  </p>
				</div>
			</div>
			
			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-to-play.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>Freedom to Play</h5>
					
					<p>Kids toys take power, and power isn't free. Except when it's from the sun. Enjoy unlimited power for smartphones using the DUO-Flex, extra battery for long car trips with the EnergyBar 250, or a magical movie night in the woods the kids will never forget with the SunSocket.</p>
				</div>
			</div>
			
			<div class="freedomgrid last">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-is-being-fully-charged.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>Freedom is Being Fully Charged</h5>
					
					<p>Never run out of juice again on a shoot. Don't drag bags and bags of batteries along for the ride; bring one: the EnergyBar 250. The high-capacity back can keep charging and charging for hours. And when it runs down, power it up with a SunSocket or EP-55 for unlimited power. Capture every moment.</p>
					
					</p>
				</div>
			</div>
			
			<div class="freedomgrid">
				<div class="gridimg">
					<img src="<?php echo $this->getSkinUrl(); ?>images/freedom-to-breathe.jpg" alt="" title="" />
				</div>
				
				<div class="divcnt">
					<h5>Freedom to Breathe</h5>
					
					<p>Re-discover the freedom to move and live your life. Take all-day power along for the ride with the EnergyBar 250. Power your CPAP device without having to worry about if there will be an outlet or not. And at only 8 pounds of weight, this is the lightest and most powerful battery you could want.</p>
				</div>
			</div>
		</div>
	</div>
</div>
