<!--start homepage-->
    <div id="homepage" class="homepage section">
    
			
			<div class="energybar" id="html-content1">
					<ul class="slides">
						<?php /* <li><img src="<?php echo $this->getSkinUrl(); ?>images/sunsocket-solar-generator.png" alt="SunSocket Solar Generator" title="" /></li> */ ?>
						<li><img src="<?php echo $this->getSkinUrl(); ?>images/energybar.png" alt="Energybar" title="" /> </li>
					</ul>
                 </div>

			 <table id="wrappertable">
      <tr>
         <td>
			 <div class="home-title">
					
						<ul id="bxsliderCaption">
							<li class="captionSlide">
							
								<?php /*
								<h1>introducing</h1>
								<h2 style="color:#fadc5a;text-shadow:0px 1px 0px #c49802;">a new source of freedom</h2>
								*/ ?>
								<h1>make every day earth day</h1>
								<h2 style="color:#fadc5a;text-shadow:0px 1px 0px #c49802;">reduce your carbon footprint</h2>
								
							</li>
							
							<?php /*
							<li class="captionSlide">
								<h1>sunsocket solar generator</h1>
								<h2 style="padding-top:0px;margin-top:0px">
									<div class="actions">
								
									<a class="linkbutton learnmore brown" href="<?php echo $this->getUrl(); ?>shop/sunsocket-solar-generator.html"><span style="font-size:20px;text-shadow:none;color:#606163;">learn more</span></a>
							
									<div style="padding-top:10px;" class="price">
										<span style="margin-left:-18px;font-size:28px;color:#606163;text-shadow:none;">$1,999</span>
									</div>
								
									<div class="clearfix"></div>
									</div>
								</h2>
							</li>
							*/ ?>
							
							
						
						</ul>
					
				</div> 
				
				<?php /*
				<script type="text/javascript">
							jQuery(window).load(function() {
									jQuery('.slides').bxSlider({
									controls:false,
									pager: true,
									speed: 1000,
									
										onSlideBefore: function (currentSlideNumber, totalSlideQty, currentSlideHtmlObject) {
										jQuery('.active-caption').hide().removeClass('active-caption');
										jQuery('#bxsliderCaption>li').eq(currentSlideHtmlObject - 1).fadeIn(1000).addClass('active-caption')
										},
												onSliderLoad: function () {
											jQuery('#bxsliderCaption>li').eq(1).fadeIn(1000).addClass('active-caption')
										},
		   
		   
		   
									auto:true,
									pagerSelector: '#pager1',
									mode: 'fade',
									captions: false,
									 buildPager: function(slideIndex){
									  switch (slideIndex){
										case 0:
										  return '<div style="float:left;margin-right:5px" class="button" id="hpprev"></div>';
										case 1:
										  return '<div style="float:left" class="button" id="hpnext"></div>';
									  }
									}
									});
							});
				</script>
				*/ ?>
				
				<script type="text/javascript">
							jQuery(window).load(function() {
									jQuery('.slides').bxSlider({
									controls:false,
									pager: false,
									speed: 1000,
									
										onSlideBefore: function (currentSlideNumber, totalSlideQty, currentSlideHtmlObject) {
										jQuery('#bxsliderCaption>li').eq(currentSlideHtmlObject - 1).fadeIn(1000).addClass('active-caption')
										},
												onSliderLoad: function () {
											jQuery('#bxsliderCaption>li').eq(0).fadeIn(1000).addClass('active-caption')
										},
		   
		   
		   
									auto:false,
									pagerSelector: '#pager1',
									mode: 'fade',
									captions: false,
									 buildPager: function(slideIndex){
									  switch (slideIndex){
										case 0:
										  return '<div style="float:left;margin-right:5px" class="button" id="hpprev"></div>';
										case 1:
										  return '<div style="float:left" class="button" id="hpnext"></div>';
									  }
									}
									});
									
									jQuery(".teaser").css({backgroundSize: "cover"});
							});
							
							
				</script>
				
				
				
				
			
			<div id="pager1">
			
			<div id="hpprev"></div>
			<div id="hpnext"></div>
			</div>
		 
			<div style="text-align:center;" id="scrollbutton">
                         <a class="navigateTo" href="#energybarinfo"></a> 
            </div>
		</td>
      </tr>
	  
	  <img class="specialgraphic" onclick="location.href='<?php echo $this->getUrl(); ?>shop.html';" style="cursor:pointer;z-index:9999;position:absolute;bottom:0px;right:0px;" src="<?php echo $this->getSkinUrl(); ?>images/specialgraphic-free-shipping.png" alt="Special" title="" /> 	 
   </table>
		
		
		

      </div>
	 <!--end homepage-->

	 <!---- ENERGYBAR INFO -->
	 
	 
     <div id="energybarinfo" class="page odd section">
         <img style="position:absolute;left:0px;" class="energybarbk" src="<?php echo $this->getSkinUrl(); ?>images/bkg_energybarinfo.jpg" alt="" title="" /> 	 
		
        <div class="content clearfix">
        
			
				<div style="width:617px;margin-right:10px;padding-right:0px;height:500px;display:block;" class="spacerdiv column_one_half">
					
					
				</div>
				
			
			
            <div style="width:510px;" class="column_one_half last box11">
				<div style="width:505px; " class="energybartext">
					<h1 class="pirulen">EnergyBar<span style="font-weight:bold;font-family:Century Gothic;font-size:12px;position: relative; bottom: 3.5ex;">TM</span> 250</h1>
						
						<strong>2.0 x 16.5 x 6.3 in.  |  8 lbs.</strong>
						
						<p class="sinfo">The EnergyBar 250 contains massive portable power that can be charged from solar panels, solar generators, wall sockets, and car lighter adapters.</p>
						
						<div class="column_one_half">
							<h2>overview</h2>
							<p>The lightest high-capacity battery pack available. Stop searching for outlets; bring your own.</p>
							<p>Discover the freedom to roam with portable power that fits in your backpack, overhead compartment, or with your gear. Power domestic or international electronic equipment up to 100 watts with the universal AC outlet, 12V lighter socket, or four USB sockets.</p>
						</div>
						
						<div class="column_one_half last">
							<h2>how it works</h2>
							<p style="overflow: visible !important; ">The EnergyBar 250 uses advanced Lithium Iron Phosphate (LiFePO4) battery technology, and is three times lighter and lasts twice as long as an equivalent lead-acid battery.</p>
							
							<p>The 20Ah (250Wh) battery can sit idle for years and only self-discharge at a minor 0-2% power per month, making it ideal for anyone from the weekend camper to the outdoors professional.</p>
						</div>
						
						<div class="clearfix"></div>
						
						<div class="actions">
							
								<a style="margin-left:20px;" class="linkbutton learnmore" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>learn more</span></a>
						
							
							
								<a class="linkbutton buyitnow" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><span>buy it now</span></a>
						
							
								<?php /*
								<div style="margin-left:25px;" class="price">
									<span>$499</span>
								</div>
								*/ ?>
							
						</div>
				</div>
          </div>
		  
		   
	
		  
   	   </div>
       
		
		 
			 
	 

     </div>
	 
	 <div id="teaser-1" class="teaser" style="background-image: url(<?php echo $this->getSkinUrl(); ?>images/bkg2.jpg);"></div>
	 <img class="teaser-1-mobile" alt="" src="<?php echo $this->getSkinUrl(); ?>images/bkg2.jpg"/>
<!--end energybarinfo content-->
      
     
	
	 
	 
	 
	 
<div id="products3" class="page odd section">  
	<div style="padding-bottom:0px !important" class="content"> 

		
			<div style="margin-bottom:0px" class="column_one_third product product1">
				<div class="pcontent">
					<h3 class="pirulen"><span style="font-size:32px;">S</span>un<span style="font-size:32px;">S</span>ocket</h3>
					<h4 class="pirulen">solar generator</h4>
					<div class="image">
					<img src="<?php echo $this->getSkinUrl(); ?>images/product-sunsocket.jpg" alt="SunSocket Solar Generator" />
					</div>	
					
					<a class="mobilecircle" href="<?php echo $this->getUrl(); ?>shop/sunsocket-solar-generator.html"><img src="<?php echo $this->getSkinUrl(); ?>images/mobile-circle-learnmore.jpg" alt="" /></a> 
					
				</div>
			</div>
			
			<div style="margin-bottom:0px" class="column_one_fourth product product2 ">	
				<div class="pcontent">
					<h3 class="pirulen">duo-flex</h3>
					<h4 style="line-height:20px;" class="pirulen">solar panel<br/>+ battery</h4>
					<div class="image">
					<img style="margin-top:-10px;" src="<?php echo $this->getSkinUrl(); ?>images/product-duo-flex-hp.jpg" alt="Duo-Flex Solar Panel + Battery" /> 
					</div>
					
					<a class="mobilecircle" href="<?php echo $this->getUrl(); ?>shop/sunsocket-duo-flex.html"><img src="<?php echo $this->getSkinUrl(); ?>images/mobile-circle-learnmore.jpg" alt="" /></a>
				</div>
			</div>
			
			<div style="margin-bottom:0px" class="column_one_third last product product3">
				<div class="pcontent">
					<h3 class="pirulen"><span style="font-size:32px;">E</span>nergy<span style="font-size:32px;">B</span>ar 250</h3>
					<h4 class="pirulen">battery pack</h4>
					<div class="image">
					<img style="padding-top:22px" src="<?php echo $this->getSkinUrl(); ?>images/product-energybar250.jpg" alt="EnergyBar 250 Solar Battery Pack" /> 
					</div>
					
					<a class="mobilecircle" href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><img src="<?php echo $this->getSkinUrl(); ?>images/mobile-circle-learnmore.jpg" alt="" /></a>
				</div>
			</div>
			
			<div class="clear"></div>


	</div>
	
	<div id="teaser-2" class="teaser fixed" style="background-image: url(<?php echo $this->getSkinUrl(); ?>images/bkg3.jpg);">
	<img class="teaser-2-mobile" alt="" src="<?php echo $this->getSkinUrl(); ?>images/bkg3.jpg"/>
	
		<div style="position:relative;z-index:9999;" class="content threec"> 
			
				<a href="<?php echo $this->getUrl(); ?>shop/sunsocket-solar-generator.html"><img class="circlehover1" alt="" src="<?php echo $this->getSkinUrl(); ?>images/bkg_circle-transpr.png" /></a> 
				<a href="<?php echo $this->getUrl(); ?>shop/sunsocket-duo-flex.html"><img class="circlehover2" alt="" title="2" src="<?php echo $this->getSkinUrl(); ?>images/bkg_circle-transpr.png" /></a>
				<a href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html"><img class="circlehover3" alt="" title="3" src="<?php echo $this->getSkinUrl(); ?>images/bkg_circle-transpr.png" /></a> 
					
				<img style="margin-left:-947px;border-left:1000px solid #fff;border-right:1000px solid #fff;" class="circles3" alt="" src="<?php echo $this->getSkinUrl(); ?>images/bkg_3circles.png" />  
				<img style="margin-left:-1000px;border-left:1000px solid #fff;border-right:1000px solid #fff;" class="circles3other" alt="" src="<?php echo $this->getSkinUrl(); ?>images/bkg_3circles2.png" />
				
				<script type="text/javascript">
				jQuery(document).ready(function(){
						jQuery('#teaser-2 img.circlehover1').mouseover(function(){
							jQuery('#teaser-2 img.circles3').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles-hover1.png');
							jQuery('#teaser-2 img.circles3other').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles2-hover1.png');
						}).mouseout(function(){
							jQuery('#teaser-2 img.circles3').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles.png');	
							jQuery('#teaser-2 img.circles3other').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles2.png');
						});
						
						jQuery('#teaser-2 img.circlehover2').mouseover(function(){
							jQuery('#teaser-2 img.circles3').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles-hover2.png');
							jQuery('#teaser-2 img.circles3other').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles2-hover2.png');
						}).mouseout(function(){
							jQuery('#teaser-2 img.circles3').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles.png');	
							jQuery('#teaser-2 img.circles3other').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles2.png');
						});
						
						jQuery('#teaser-2 img.circlehover3').mouseover(function(){
							jQuery('#teaser-2 img.circles3').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles-hover3.png');
							jQuery('#teaser-2 img.circles3other').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles2-hover3.png');
						}).mouseout(function(){
							jQuery('#teaser-2 img.circles3').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles.png');	
							jQuery('#teaser-2 img.circles3other').attr('src', '<?php echo $this->getSkinUrl(); ?>images/bkg_3circles2.png');
						});
				});
				</script>
				
				
						
				
				
				

		</div>
    </div>

</div>






 
	 
	 
<!-- start aboutus --> 
     <div id="aboutus" class="page odd section">
 
        <div class="content clearfix">
			<div class="column_one_third aspectlogo">
				<img src="<?php echo $this->getSkinUrl(); ?>images/aspect-solar-logo2.png" alt="Aspect Solar" />
			</div>
			
			<div class="column_two_thirds last abouttext">
				<div class="abouttextc">
					<p><span class="mediumstrong">Smart enough to bring technology along for the ride,</span><br/>and not let it get in the way.</span></p>
					
					<p class="small">AspectSolar is a pioneer of portable solar energy products, providing lifestyle solutions to the rest of the pioneers out there. Our products help people stay connected while getting away. Everything warmed by the light of the sun was put here for us to explore. AspectSolar supports the pioneers, the nomads, and the discoverers by removing the boundaries that keep them from going further.</p>
					
					<div class="actions">
						<a class="linkbutton learnmore" href="<?php echo $this->getUrl(); ?>learn/how-it-works"><span>learn more</span></a>
					</div>
				</div>
			</div>
			
			<div class="clear"></div>
			
			<div class="videos">
			

				
				<div class="column_one_third video video1">
				
				
				
				
				
				
				
				
				<?php
				/* USER-AGENTS
				================================================== */
				function check_user_agent ( $type = NULL ) {
						$user_agent = strtolower ( $_SERVER['HTTP_USER_AGENT'] );
						if ( $type == 'bot' ) {
								// matches popular bots
								if ( preg_match ( "/googlebot|adsbot|yahooseeker|yahoobot|msnbot|watchmouse|pingdom\.com|feedfetcher-google/", $user_agent ) ) {
										return true;
								}
						} else if ( $type == 'browser' ) {
								if ( preg_match ( "/mozilla\/|opera\//", $user_agent ) ) {
										return true;
								}
						} else if ( $type == 'mobile' ) {
								if ( preg_match ( "/android/i", $user_agent ) ) {
										return true;
								} 
								}
						return false;
				}

				?>

				
					<a class="fancyboxvideoimg fancyboxvideo iframe" href="http://www.youtube.com/embed/qEFzyVTCibY"><img src="<?php echo $this->getSkinUrl(); ?>images/video1.jpg" alt="energybar features" /></a>
					
					
					
					
					<?php
					$isandroid = check_user_agent('mobile');
					if($isandroid) {
							?> 
							
							<div class="youtube-player" id='youtube-player-container-qEFzyVTCibY'> </div> 
							
							<script type="text/javascript">
								jQuery("#youtube-player-container-qEFzyVTCibY").tubeplayer({
									width: 330, // the width of the player
									height: 174, // the height of the player
									allowFullScreen: "true", // true by default, allow user to go full screen
									wmode: "transparent", // note: transparent maintains z-index, but disables GPU acceleration
									swfobjectURL: "http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js",
									loadSWFObject: true, // if you include swfobject, set to false
									iframed: false,
									theme: "light", // possible options: "dark" or "light"
									color: "white",
									autoHide: false,
									modestbranding: false,
									initialVideo: "qEFzyVTCibY", // the video that is loaded into the player
									preferredQuality: "default"// preferred quality: default, small, medium, large, hd720,

								});
								
								jQuery(document).ready(function(){
									jQuery(".video .playbutton").remove();
									jQuery(".video .fancyboxvideoimg").remove();
									jQuery(".product-view .videoimg").remove();
								});
							</script>

							<?php
						}
					?>
					
					
					
					<a class="videoview fancyboxvideo iframe" href="http://www.youtube.com/embed/qEFzyVTCibY"><span>EnergyBar 250</span></a>
					<a class="playbutton fancyboxvideo iframe" href="http://www.youtube.com/embed/qEFzyVTCibY"></a>

				</div>
				
				<div class="column_one_third video video2">
				
   
					<a class="fancyboxvideoimg fancyboxvideo iframe" href="http://www.youtube.com/embed/LpEAIBFIm9E"><img src="<?php echo $this->getSkinUrl(); ?>images/video2.jpg" alt="sunsocket in action" /></a>
					
					
					
					
					<?php
					$isandroid = check_user_agent('mobile');
					if($isandroid) {
							?> 
							
							<div class="youtube-player" id='youtube-player-container-LpEAIBFIm9E'> </div>
							
							<script type="text/javascript">
							jQuery("#youtube-player-container-LpEAIBFIm9E").tubeplayer({
								width: 330, // the width of the player
								height: 174, // the height of the player
								allowFullScreen: "true", // true by default, allow user to go full screen
								wmode: "transparent", // note: transparent maintains z-index, but disables GPU acceleration
								swfobjectURL: "http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js",
								loadSWFObject: true, // if you include swfobject, set to false
								iframed: false,
								theme: "light", // possible options: "dark" or "light"
								color: "white",
								autoHide: false,
								modestbranding: false,
								initialVideo: "LpEAIBFIm9E", // the video that is loaded into the player
								preferredQuality: "default"// preferred quality: default, small, medium, large, hd720,

							});
							</script>

							<?php
						}
					?>
					
					
					
					
					
					<a class="videoview fancyboxvideo iframe" href="http://www.youtube.com/embed/LpEAIBFIm9E"><span>Sun-tracking Technology</span></a>
					<a class="playbutton fancyboxvideo iframe" href="http://www.youtube.com/embed/LpEAIBFIm9E"></a>
				</div>
				
				<div class="column_one_third last video video3">
					<a class="fancyboxvideoimg fancyboxvideo iframe" href="http://www.youtube.com/embed/P1umuZfFMkk#t=132"><img src="<?php echo $this->getSkinUrl(); ?>images/video3.jpg" alt="our energy bar in action" /></a>
					
					
					
					
					
					<?php
					$isandroid = check_user_agent('mobile');
					if($isandroid) {
							?> 
							
							<div class="youtube-player" id='youtube-player-container-P1umuZfFMkk'> </div>
							
							<script type="text/javascript">
							jQuery("#youtube-player-container-P1umuZfFMkk").tubeplayer({
								width: 330, // the width of the player
								height: 174, // the height of the player
								allowFullScreen: "true", // true by default, allow user to go full screen
								wmode: "transparent", // note: transparent maintains z-index, but disables GPU acceleration
								swfobjectURL: "http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js",
								loadSWFObject: true, // if you include swfobject, set to false
								iframed: false,
								theme: "light", // possible options: "dark" or "light"
								color: "white",
								autoHide: false,
								modestbranding: false,
								initialVideo: "P1umuZfFMkk", // the video that is loaded into the player
								preferredQuality: "default"// preferred quality: default, small, medium, large, hd720,


							});
							</script>

							<?php
						}
					?>
					
				
					
					
					
					<a class="videoview fancyboxvideo iframe" href="http://www.youtube.com/embed/P1umuZfFMkk#t=132"><span>The EnergyBar 250 in Action</span></a>
					<a class="playbutton fancyboxvideo iframe" href="http://www.youtube.com/embed/P1umuZfFMkk#t=132"></a>
				</div>
				
				<div class="clear"></div>
				
			
				
				
				
	
				
			</div>
			
			<div class="abouttitle">
				<h2>freedom is being fully <span class="yellow">charged</span></h2>
			</div>
        	
            
     	</div>    
        
     </div>
<!-- end aboutus --> 
    
    


    <div id="teaser-3" class="teaser" style="background-image: url(<?php echo $this->getSkinUrl(); ?>images/bkg4.jpg);">
	
	 <div id="footervid" class="page" style="background:transparent !important;overflow:visible !important;height:auto">
		 <div class="content clearfix">
				<div class="videos">
					
			
				<?php 
					print $this->getLayout()
					 ->createBlock("wordpress/sidebar_widget_posts")
					 ->setTemplate("wordpress/sidebar/widget/posts-homepage.phtml")
					 ->toHtml(); 
				 ?>
			
				
					
					<div class="clear"></div>
				</div>
		 </div>
		
	 
	 </div>
	 
	
     </div>