<div class="inner-fullwidth">
 
	<div class="title">
		<h2>awards</h2>
		
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('block_social_icons')->toHtml() ?>
	</div>
	
	<div class="contentbox">
		<img style="margin-top:-3px;margin-right:15px;float:left;" src="<?php echo $this->getSkinUrl(); ?>images/CES-Award.jpg" alt="" title="" /> 
		<h3>2014 CES Innovation Awards</h3>

		<p>AspectSolar's SunSocket Solar Generator was honored by the CES Innovation Awards in January of 2014. In recognition of its advances in portable power, the judges selected the Solar Generator as a leader in innovation. It was the first product in AspectSolar's line and it debuted our commitment to advanced technology. The generator utilized both highly-efficient monocrystalline PV cells on its solar panels and a lightweight LiFePO4 battery. Never before had portable power like that fit into the size of a briefcase and weighed barely 25 lbs. </p>

		<p>Beyond that, the SunSocket Solar Generator was the first in the world to use sun-tracking technology to follow the arc of the sun across the sky throughout the day. This was the only solar generator in the world to use sun-tracking technology at the time. With optimal positioning all day long, the SunSocket Solar Generator could charge its own massive battery in only 5 hours of sunlight.</p>



	</div>
	
	
</div>

