<div class="page-title">

		<h1>learn</h1>
</div>
	


<div class="inner-left">
	<div class="title"><h2>how does <span style="color:#f6c221;">solar power</span> work?</h2></div>
	<div class="contentbox">
	
		 
							
			
			<div class="column_one_third">
				<div class="column1">
					<div class="imgicon">
					<img src="<?php echo $this->getSkinUrl(); ?>images/how-it-works-icon1.png" alt="" title="" />    
					</div>			
					<h4 class="style1">solar panels convert light<br/>into electrical energy</h4>
				</div>
			</div>
			
			<div class="column_one_third">
				<div class="column2">
					<div class="imgicon">
					<img src="<?php echo $this->getSkinUrl(); ?>images/how-it-works-icon2.png" alt="" title="" /> 
					</div>
					<h4 class="style1">battery packs<br/>store generated power</h4>			
				</div>
			</div>
			
			<div class="column_one_third last">
				<div class="column3">
					<div class="imgicon">
					<img src="<?php echo $this->getSkinUrl(); ?>images/how-it-works-icon3.png" alt="" title="" />
					</div>
					<h4 class="style1">use that power<br/>when you need to</h4>			
				</div>
			</div>
			
			<div class="clear"></div>
			
			
							
			
			<p>Photovoltaic (PV) cells absorb solar energy and convert it into usable electricity. The silicon that makes up these PV cells is a semi-conductor that, when exposed to solar rays, has electrons that absorb energy and become excited. By using two metal contacts on either side of a PV cell, the electrical current created by the electrons can be drawn out into a battery and stored for later use. In larger solar farms, this current is fed into the grid. Whether on a large scale or with your own personal panels, you use that electricity to power electronic devices.</p>
			
			
			<?php /*
			<p>We can draw this current by placing metal contacts on each side of the solar cell.   We then feed this electrical current directly to a battery to store the energy so that you can power or charge your electronic devices.  This whole process is what makes up a "solar generator."  Our SunSocket&#0153;  solar generator takes it one step further by utilizing a proprietary sun-tracking system, which orients our solar cells to face directly to the sun,which maximizes the amount of energy converted from the sun throughout the day.</p>
		
		
		<h3>BIGGER BATTERY <img src="<?php echo $this->getSkinUrl(); ?>images/text-notequal.gif" alt="" title="" />  MORE POWER.</h3>
		
		<p>A solar generator is like a bucket of water with a tap.  The water is the energy collected from sunlight.  If the amount of energy collected from the sun is less than the amount of energy that is used to power your electronic devices, then you will run out of energy!  It doesn't matter how big the battery is in your solar generator if there isn't enough energy to keep the battery charged.  </p>
		
		<img class="floatleft" src="<?php echo $this->getSkinUrl(); ?>images/water-energy-info.jpg" alt="" title="" />
		<div style="float:left;margin-left:auto">
			<h3>THE POWER IS IN THE SOLAR PANELS</h3>
			<p style="width:348px;">The more energy that is being collected from the sun and converted to electricity, the longer the battery in your solar generator will stay charged.  With no new energy being collected, your battery becomes a paper weight.  </p>
			
			<h4 class="boldgray">Powering a 50-Watt Laptop:</h4>
			<p><span style="line-height:22px;color:#606163;font-weight:bold;">500Wh Battery and a 10-Watt PV Panel, 500Wh / (50W-10W) = 12.5 Hours</span><br/>
			<span style="line-height:22px;color:#279dff;font-weight:bold;">250Wh Battery and a 40-Watt PV Panel, 250Wh / (50W-40W) = 25 Hours</span>
			</p>
			<p style="margin-top:-3px;"><span style="color:#606163;font-weight:bold;">Conclusion?  More PV = More Power</span></p>
			
		</div>
		
		<div class="clear"></div>
		
		*/ ?>
		
		<h3 style="text-transform:none" class="grey-23">AspectSolar uses the most <span style="color:#f6c221;">advanced technology</span> available</h3>
		
		
		
		
		
		
		
		
		
		
		<div class="floatlefticon">
		<img src="<?php echo $this->getSkinUrl(); ?>images/icon-mono.jpg" alt="" title="" />
		</div>
		<h3>Monocrystalline Solar Cells</h3>
		<p>These PV cells have the highest efficiency compared to polycrystalline and thin film cells. Monocrystalline can achieve 11-22% efficiency - almost double the range of what polycrystalline cells can produce. This is the most efficient solar cell available for consumer products right now. We get excited about advances in solar technology, though; almost as excited as you get about new AspectSolar products. As more powerful technology becomes available, we'll roll out new releases to match.</p>

		
		<div class="box1">
			<div class="box1content">
				<div class="box1left">

					<ul class="line">
						<li>19% Efficiency</li>
						<li>Quick charging</li>
						<li>More power, less space</li>
					</ul>
				</div>
				
				<div class="box1right">
					<h4 class="boldgray">Found in:</h4>
					<ul class="line">
						<li><a href="<?php echo $this->getUrl(); ?>shop/sunsocket-ep-55.html">EP-55</a>, <a href="<?php echo $this->getUrl(); ?>shop/sunsocket-duo-flex.html">DUO-Flex</a>, <a href="<?php echo $this->getUrl(); ?>shop/sunsocket-solar-generator.html">SunSocket Solar Generator</a></li>
					</ul>
				</div>
				
				<div class="clear"></div>
			</div>
		</div>
		
		
		
		
		

		
		
		
		
		
		
		
		<div class="floatlefticon">
		<img src="<?php echo $this->getSkinUrl(); ?>images/icon-12v.jpg" alt="" title="" />
		</div>
		<h3>LiFePO4 Battery</h3>
		<p>Batteries come in all shapes and sizes, but we use only the most efficient technology for our systems. A Lithium Iron Phosphate battery, or LiFePO4 for short, is the best battery available for high-capacity portable needs. Cheaper lead-acid batteries are very common in solar generator solutions, but they last half as long, are not as safe as LiFePO4s, and are much heavier. A 250Wh lead-acid battery may weigh up to 20 lbs. For truly portable solar technology, that's not acceptable. </p>
		
		<div class="box1">
			<div class="box1content">
				<div class="box1left">
					<ul class="line">
						<li>Much lighter</li>
						<li>Double-to-triple the lifespan of lead-acid batteries</li>
						<li>0-2% discharge per month</li>
					</ul>
				</div>
				
				<div class="box1right">
					<h4 class="boldgray">Found in:</h4>
					<ul class="line">
						<li><a href="<?php echo $this->getUrl(); ?>shop/sunsocket-energybar-250.html">EnergyBar250</a>, <a href="<?php echo $this->getUrl(); ?>shop/sunsocket-solar-generator.html">SunSocket Solar Generator</a></li>
					</ul>
				</div>
				
				<div class="clear"></div>
			</div>
		</div>
		
		
		
		
		
		
		
		
		
		<div class="floatlefticon">
		<img src="<?php echo $this->getSkinUrl(); ?>images/icon-sun-track.jpg" alt="" title="" />
		</div>
		<h3>SOLTRAX&trade; Sun-Tracking Technology</h3>
		<p>The sun moves throughout the day, why shouldn't your solar panels? Traditional consumer solar panels will get optimum sunlight for only a few hours per day without being repositioned. For those who don't want to be tied down by plugs or static panels, the sun-tracking technology in our <a href="<?php echo $this->getUrl(); ?>inspire/awards">CES Innovation Award-winning</a> SunSocket Solar Generator will rotate the panels to follow the sun's path across the sky. You can go for an all-day hike and still come home to a fully charged battery.</p>
		
		<div class="box1">
			<div class="box1content">
				<div class="box1left">
					<ul class="line">
						<li>Maximizes the amount of solar energy converted into electricity</li>
						<li>Requires less attention throughout the day</li>
						<li>Consistent charge</li>
					</ul>
				</div>
				
				<div class="box1right">
					<h4 class="boldgray">Found in:</h4>
					<ul class="line">
						<li><a href="<?php echo $this->getUrl(); ?>shop/sunsocket-solar-generator.html">SunSocket Solar Generator</a></li>
					</ul>
				</div>
				
				<div class="clear"></div>
			</div>
		</div>
		
		
		<div class="floatlefticon">
		<img src="<?php echo $this->getSkinUrl(); ?>images/icon-solmax.jpg" alt="" title="" />
		</div>

		<h3>Maximum Power Point Tracking Technology</h3>
		<p>Maximum Power Point Tracking (MPPT) regulates the electrical field within solar panels to ensure that a maximum charge is being drawn out at any given time. Environmental conditions like partial shade or inconsistent cloud cover hamper the electrical conversion process. With our technology, any slowdown is minimized. Our MPPT also includes an LED that lights up when the panels are angled in such a way to receive maximum light.</p>
		
		<div class="box1">
			<div class="box1content">
				<div class="box1left">
					<ul class="line">
						<li>Regulates electrical conversion</li>
						<li>Charges more efficiently</li>
					</ul>
				</div>
				
				<div class="box1right">
					<h4 class="boldgray">Found in:</h4>
					<ul class="line">
						<li><a href="<?php echo $this->getUrl(); ?>shop/sunsocket-ep-55.html">EP-55</a></li>
					</ul>
				</div>
				
				<div class="clear"></div>
			</div>
		</div>
		
		
		
		
		
		


	</div>
</div>
