
<div class="block block_socialicons">
	
		<span>LIKE IT? SHARE IT!</span>
		<div onclick="window.open('https://www.facebook.com/AspectSolarMedia','_blank');" class="fb"></div>
		<div onclick="window.open('https://plus.google.com/+AspectSolarHQ','_blank');" class="google"></div>
		<div onclick="window.open('https://twitter.com/aspectsolar','_blank');" class="twitter"></div>
		<div onclick="window.open('http://www.youtube.com/aspectsolarhq','_blank');" class="last youtube"></div>
	
</div>
<div class="clear"></div>

						