<?php $hint = htmlspecialchars(trim($this->getField()->getHint())); ?>
<?php if ($this->getFieldValue()) $hint = false; ?>
<textarea name='<?php echo $this->getFieldName()?>' id='<?php echo $this->getFieldId()?>'
          class='<?php echo $this->getFieldClass()?> <?php if($hint){ echo 'webforms-fields-hint';}?>'
          style='<?php echo $this->getFieldStyle()?>' <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?>
          <?php if($hint){?>onfocus="if(!this.haswriting){this.value='';}" onblur="if(!this.value){this.haswriting=false;}else{this.haswriting=true};" style="if (this.value == '<?php echo str_replace("'","\'",$hint)?>') {this.value = ''; $(this).removeClassName('webforms-fields-hint');}" onblur="if (this.value == '') {this.value = '<?php echo str_replace("'","\'",$hint)?>'; $(this).addClassName('webforms-fields-hint');}"<?php } ?>  <?php if ($hint) { echo 'placeholder="'.$hint.'"'; } ?> ></textarea>

