<?php $hint = htmlspecialchars(trim($this->getField()->getHint())); ?>
<?php if ($this->getFieldValue()) $hint = false; ?>
<input type='text' name='<?php echo $this->getFieldName() ?>' id='<?php echo $this->getFieldId() ?>'
       class='<?php echo $this->getFieldId() ?> <?php echo $this->getFieldClass() ?> <?php if($hint){ echo 'webforms-fields-hint';}?>' style='<?php echo $this->getFieldStyle() ?>'
       value="<?php echo $hint; ?>"
       <?php if ($this->getField()->getType() == 'email'){ ?> onkeyup="if(this.value.search(' ')>=0){this.value = this.value.replace(' ','');}"<?php } ?>
       <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?>
	  
	   
	  onblur="if (this.value=='') {this.value='<?php echo $hint; ?>'};" onfocus="if (this.value=='<?php echo $hint; ?>') {this.value=''};" 
	   />
	   
	   
	   
	  

	   